export type NotificationType =
  // Finder
  | "FINDER_LEAD_RECEIVED"
  | "FINDER_QUOTE_SENT"
  | "FINDER_DEAL_WON"
  | "FINDER_DEAL_LOST"
  | "FINDER_MONEY_AVAILABLE"
  | "FINDER_PAYOUT_PAID"
  | "FINDER_RANK_UP"
  | "FINDER_BONUS"
  | "FINDER_WARNING"
  // Business
  | "BUSINESS_NEW_LEAD"
  | "BUSINESS_RESPONSE_REMINDER"
  | "BUSINESS_APPROVED"
  | "BUSINESS_REJECTED"
  | "BUSINESS_INVOICE"
  | "BUSINESS_INVOICE_REMINDER"
  | "BUSINESS_SUSPENDED"
  | "BUSINESS_REINSTATED"
  | "BUSINESS_BUDGET_REACHED"
  | "BUSINESS_DISPUTE"
  // Customer
  | "CUSTOMER_REQUEST_RECEIVED"
  | "CUSTOMER_CONFIRM_JOB"
  // Admin
  | "ADMIN_NEW_BUSINESS"
  | "ADMIN_DISPUTE"
  | "ADMIN_PAYOUT_REQUEST"
  | "ADMIN_REPORT"
  | "ADMIN_FRAUD_FLAG";

export type NotificationData = Record<string, string | number | undefined>;
