import type { FeeRule } from "@/lib/fees";

/**
 * Launch categories, grouped by sector. `example` is a worked example used on marketing pages:
 * a typical job amount and a plausible fee rule. It is labelled as an example everywhere; real
 * fees come from each business's own campaign.
 */
export type CategoryGroup = "wonen" | "energie" | "buiten" | "auto" | "events" | "sport" | "zakelijk" | "leren" | "diensten" | "winkels" | "horeca" | "reizen";

export const CATEGORY_GROUPS: { key: CategoryGroup; nl: string; en: string }[] = [
  { key: "wonen", nl: "Wonen & verbouwen", en: "Home & renovation" },
  { key: "energie", nl: "Energie & duurzaam", en: "Energy & sustainability" },
  { key: "buiten", nl: "Tuin & buiten", en: "Garden & outdoor" },
  { key: "auto", nl: "Auto & vervoer", en: "Cars & mobility" },
  { key: "events", nl: "Bruiloft & events", en: "Weddings & events" },
  { key: "sport", nl: "Sport & lifestyle", en: "Sport & lifestyle" },
  { key: "zakelijk", nl: "Zakelijk & tech", en: "Business & tech" },
  { key: "leren", nl: "Lessen & opleiding", en: "Lessons & training" },
  { key: "diensten", nl: "Diensten aan huis", en: "Home services" },
  { key: "winkels", nl: "Winkels & webshops", en: "Shops & e-commerce" },
  { key: "horeca", nl: "Eten & horeca", en: "Food & hospitality" },
  { key: "reizen", nl: "Reizen & vrije tijd", en: "Travel & leisure" },
];

export interface CategoryDef {
  slug: string;
  group: CategoryGroup;
  nameNl: string;
  nameEn: string;
  descriptionNl: string;
  descriptionEn: string;
  whoNl: string;
  whoEn: string;
  exampleJobCents: number;
  example: FeeRule;
}

const pct = (bps: number, minJob = 50_000, minFee = 5_000): FeeRule => ({ feeType: "PERCENTAGE", feePercentBps: bps, minJobAmountCents: minJob, minFeeCents: minFee });
const fixed = (cents: number, minJob = 0): FeeRule => ({ feeType: "FIXED", feeFixedCents: cents, minJobAmountCents: minJob, minFeeCents: 0 });
const tiers = (minJob: number, ...t: [number, number][]): FeeRule => ({ feeType: "TIERED", tiers: t.map(([fromCents, feeCents]) => ({ fromCents, feeCents })), minJobAmountCents: minJob, minFeeCents: 5_000 });
const eur = (n: number) => n * 100;

type Row = [slug: string, group: CategoryGroup, nl: string, en: string, descNl: string, descEn: string, whoNl: string, whoEn: string, jobEur: number, rule: FeeRule];

const ROWS: Row[] = [
  // Wonen & verbouwen
  ["schilders", "wonen", "Schilders", "Painters", "Binnen- en buitenschilderwerk, kozijnen, houtrot.", "Interior and exterior painting, window frames, wood rot.", "Iemand wiens kozijnen bladderen, of die net een huis heeft gekocht.", "Someone whose window frames are peeling, or who just bought a house.", 5_000, pct(1000)],
  ["stukadoors", "wonen", "Stukadoors", "Plasterers", "Wanden en plafonds stucen, spackspuiten, sierpleister.", "Plastering walls and ceilings, spray finishes, decorative plaster.", "Iemand die gaat verbouwen of een oud huis opknapt.", "Someone renovating or doing up an old house.", 3_000, pct(1000)],
  ["loodgieters", "wonen", "Loodgieters", "Plumbers", "Leidingwerk, afvoer, lekkages, sanitair.", "Pipework, drains, leaks, sanitary fittings.", "Iemand met een lekkage, een verstopte afvoer of een nieuwe aansluiting.", "Someone with a leak, a blocked drain or a new connection.", 1_200, pct(1000)],
  ["dakdekkers", "wonen", "Dakdekkers", "Roofers", "Dakrenovatie, bitumen, dakpannen, dakgoten.", "Roof renovation, bitumen, tiles, gutters.", "Iemand met een lekkend dak of een plat dak dat aan vervanging toe is.", "Someone with a leaking roof or a flat roof due for replacement.", 8_000, pct(800)],
  ["elektriciens", "wonen", "Elektriciens", "Electricians", "Groepenkast, bekabeling, verlichting, storingen.", "Fuse boxes, wiring, lighting, faults.", "Iemand met een groepenkast die te klein is, of die gaat verbouwen.", "Someone with an undersized fuse box, or renovating.", 2_500, pct(1000)],
  ["badkamers", "wonen", "Badkamers", "Bathrooms", "Complete badkamerrenovatie, tegelwerk, sanitair.", "Complete bathroom renovation, tiling, fixtures.", "Iemand met een gedateerde badkamer of een nieuwbouwwoning.", "Someone with a dated bathroom or a new-build home.", 12_000, pct(600)],
  ["keukens", "wonen", "Keukens", "Kitchens", "Keukens op maat, montage, werkbladen, apparatuur.", "Custom kitchens, fitting, worktops, appliances.", "Iemand die verhuist of zijn keuken wil vervangen.", "Someone moving house or replacing their kitchen.", 15_000, tiers(eur(5_000), [eur(5_000), eur(250)], [eur(10_000), eur(500)], [eur(20_000), eur(800)])],
  ["kozijnen", "wonen", "Kozijnen", "Window frames", "Kunststof, houten en aluminium kozijnen, deuren, glas.", "uPVC, wooden and aluminium frames, doors, glazing.", "Iemand met tochtige ramen of enkel glas.", "Someone with draughty windows or single glazing.", 10_000, pct(600)],
  ["tegelzetters", "wonen", "Tegelzetters", "Tilers", "Wand- en vloertegels, natuursteen, grootformaat tegels.", "Wall and floor tiles, natural stone, large-format tiles.", "Iemand die een nieuwe vloer of badkamer wil.", "Someone who wants a new floor or bathroom.", 4_000, pct(1000)],
  ["timmerlieden", "wonen", "Timmerlieden", "Carpenters", "Trappen, kasten, aftimmeren, houten vloeren.", "Stairs, cupboards, finishing carpentry, wooden floors.", "Iemand die maatwerk in huis wil.", "Someone who wants custom woodwork at home.", 3_500, pct(1000)],
  ["aannemers", "wonen", "Aannemers & aanbouw", "Builders & extensions", "Aanbouw, uitbouw, verbouwing van A tot Z.", "Extensions and full renovations from A to Z.", "Een gezin dat meer ruimte nodig heeft.", "A family that needs more space.", 45_000, tiers(eur(10_000), [eur(10_000), eur(750)], [eur(30_000), eur(1_500)], [eur(60_000), eur(2_500)])],
  ["dakkapellen", "wonen", "Dakkapellen", "Dormers", "Prefab en op maat gemaakte dakkapellen.", "Prefab and custom dormers.", "Iemand die een zolder bruikbaar wil maken.", "Someone who wants a usable attic.", 9_000, fixed(eur(600), eur(5_000))],
  ["vloeren", "wonen", "Vloeren", "Flooring", "PVC, laminaat, parket, gietvloeren.", "Vinyl, laminate, parquet, poured floors.", "Iemand die verhuist of een nieuwe vloer zoekt.", "Someone moving or looking for a new floor.", 4_500, pct(1000)],
  ["dekvloeren", "wonen", "Dekvloeren", "Screed floors", "Zandcement en anhydriet dekvloeren, in één dag gelegd.", "Sand-cement and anhydrite screeds, laid in one day.", "Iemand die gaat bouwen, verbouwen of vloerverwarming laat leggen.", "Someone building, renovating or installing underfloor heating.", 3_500, pct(1000)],
  ["isolatie", "wonen", "Isolatie", "Insulation", "Spouw-, vloer- en dakisolatie.", "Cavity, floor and roof insulation.", "Iemand met een koud huis of hoge stookkosten.", "Someone with a cold house or high heating bills.", 3_000, pct(1000)],
  ["interieurbouw", "wonen", "Interieurbouw", "Interior joinery", "Maatkasten, wandmeubels, inloopkasten.", "Fitted wardrobes, wall units, walk-in closets.", "Iemand die zijn huis wil inrichten met maatwerk.", "Someone furnishing their home with custom pieces.", 6_000, pct(1000)],
  ["raambekleding", "wonen", "Gordijnen & raambekleding", "Curtains & blinds", "Gordijnen, jaloezieën, plissés, inmeten en ophangen.", "Curtains, blinds, pleated shades, measured and fitted.", "Iemand die net is verhuisd.", "Someone who just moved.", 2_000, pct(1000)],
  ["zonwering", "wonen", "Zonwering & rolluiken", "Awnings & shutters", "Screens, knikarmschermen, rolluiken, uitvalschermen.", "Screens, awnings, roller shutters.", "Iemand met een warme zuidgevel.", "Someone with a hot south-facing facade.", 3_500, pct(1000)],
  ["glaszetters", "wonen", "Glaszetters", "Glaziers", "HR++ en triple glas, glasschade, glazen wanden.", "Double and triple glazing, glass damage, glass walls.", "Iemand met enkel glas of een gebroken ruit.", "Someone with single glazing or a broken pane.", 2_500, pct(1000)],
  ["garagedeuren", "wonen", "Garagedeuren", "Garage doors", "Sectionaal-, kantel- en roldeuren, elektrisch.", "Sectional, up-and-over and roller doors, motorised.", "Iemand met een oude of kapotte garagedeur.", "Someone with an old or broken garage door.", 2_500, fixed(eur(200), eur(1_000))],
  ["beveiliging", "wonen", "Beveiliging & alarm", "Security & alarms", "Alarmsystemen, camera's, slimme sloten.", "Alarm systems, cameras, smart locks.", "Iemand na een inbraak in de buurt.", "Someone after a break-in nearby.", 1_500, pct(1200)],
  ["domotica", "wonen", "Domotica & smart home", "Smart home", "Slimme verlichting, verwarming en audio in huis.", "Smart lighting, heating and audio at home.", "Iemand die zijn huis slimmer wil maken.", "Someone who wants a smarter home.", 4_000, pct(1000)],
  // Energie & duurzaam
  ["installateurs", "energie", "Installateurs (cv/warmtepomp)", "Installers (heating/heat pumps)", "Cv-ketels, warmtepompen, ventilatie.", "Boilers, heat pumps, ventilation.", "Iemand met een oude cv-ketel of die wil verduurzamen.", "Someone with an old boiler or who wants to go sustainable.", 9_000, pct(800)],
  ["zonnepanelen", "energie", "Zonnepanelen", "Solar panels", "Zonnepanelen en omvormers, complete installatie.", "Solar panels and inverters, fully installed.", "Huiseigenaren met een geschikt dak die hun energierekening omlaag willen.", "Homeowners with a suitable roof who want lower energy bills.", 7_000, tiers(eur(3_000), [eur(3_000), eur(300)], [eur(10_000), eur(500)])],
  ["thuisbatterijen", "energie", "Thuisbatterijen", "Home batteries", "Opslag voor zonnestroom, slim laden en ontladen.", "Storage for solar power, smart charging.", "Iemand met zonnepanelen die meer zelf wil gebruiken.", "Someone with solar panels who wants to use more themselves.", 6_000, fixed(eur(450), eur(3_000))],
  ["laadpalen", "energie", "Laadpalen", "EV chargers", "Thuisladers en zakelijke laadpunten.", "Home chargers and business charge points.", "Iemand die net een elektrische auto heeft.", "Someone who just got an electric car.", 1_800, fixed(eur(175), eur(1_000))],
  ["airco", "energie", "Airco", "Air conditioning", "Split-units, multi-split, koelen en verwarmen.", "Split units, multi-split, cooling and heating.", "Iemand met een warme slaapkamer of zolder.", "Someone with a hot bedroom or attic.", 2_800, pct(1200)],
  // Tuin & buiten
  ["hoveniers", "buiten", "Hoveniers", "Gardeners", "Tuinaanleg, beplanting, onderhoud.", "Garden design, planting, maintenance.", "Iemand die een nieuwe tuin wil of net een huis met tuin kocht.", "Someone who wants a new garden or just bought a house with one.", 6_000, pct(1000)],
  ["bestrating", "buiten", "Bestrating", "Paving", "Opritten, terrassen, sierbestrating.", "Driveways, patios, decorative paving.", "Iemand met een verzakte oprit of een nieuw terras in gedachten.", "Someone with a sunken driveway or planning a new patio.", 5_000, pct(1000)],
  ["schuttingen", "buiten", "Schuttingen & hekwerk", "Fences & gates", "Houten, betonnen en composiet schuttingen, poorten.", "Wooden, concrete and composite fences, gates.", "Iemand met een omgewaaide schutting.", "Someone whose fence blew down.", 2_500, pct(1000)],
  ["overkappingen", "buiten", "Overkappingen & veranda's", "Verandas & canopies", "Aluminium veranda's, glazen schuifwanden, carports.", "Aluminium verandas, glass sliding walls, carports.", "Iemand die langer buiten wil zitten.", "Someone who wants to sit outside longer.", 9_000, fixed(eur(650), eur(4_000))],
  ["zwembaden", "buiten", "Zwembaden & wellness", "Pools & wellness", "Zwembaden, jacuzzi's, buitensauna's.", "Pools, hot tubs, outdoor saunas.", "Iemand met een grote tuin en een wens.", "Someone with a big garden and a wish.", 25_000, tiers(eur(5_000), [eur(5_000), eur(500)], [eur(20_000), eur(1_500)])],
  ["bomen", "buiten", "Boomverzorging", "Tree care", "Bomen kappen, snoeien, stobben frezen.", "Tree felling, pruning, stump grinding.", "Iemand met een te grote boom in de tuin.", "Someone with a tree that has grown too big.", 1_200, pct(1200)],
  // Auto & vervoer
  ["autodealers", "auto", "Autodealers", "Car dealers", "Nieuwe en gebruikte auto's, inruil.", "New and used cars, trade-ins.", "Iemand die binnenkort een andere auto zoekt.", "Someone looking for a different car soon.", 18_000, fixed(eur(400), eur(3_000))],
  ["private-lease", "auto", "Private & zakelijke lease", "Private & business lease", "Leasecontracten voor particulieren en ondernemers.", "Lease contracts for private and business drivers.", "Iemand die zonder grote aankoop wil rijden.", "Someone who wants to drive without a big purchase.", 15_000, fixed(eur(300))],
  ["autoschade-garages", "auto", "Autoschade en garages", "Car repair and garages", "Schadeherstel, onderhoud, APK, banden.", "Body repair, servicing, MOT, tyres.", "Iemand met een deuk, kras of een auto die onderhoud nodig heeft.", "Someone with a dent, scratch or a car due for service.", 1_200, pct(1000)],
  ["auto-detailing", "auto", "Auto-detailing & wrapping", "Car detailing & wrapping", "Poetsen, coaten, wrappen en ramen tinten.", "Polishing, coating, wrapping and window tinting.", "Iemand die zijn auto als nieuw wil.", "Someone who wants their car to look new.", 1_500, pct(1200)],
  ["e-bikes", "auto", "E-bikes & scooters", "E-bikes & scooters", "Elektrische fietsen, speed pedelecs, scooters.", "Electric bikes, speed pedelecs, scooters.", "Iemand die elektrisch naar werk wil.", "Someone who wants to commute electric.", 3_000, fixed(eur(150), eur(1_000))],
  ["campers", "auto", "Campers & caravans", "Campers & caravans", "Verkoop, verhuur en onderhoud.", "Sales, rental and servicing.", "Een stel dat er vaker op uit wil.", "A couple that wants to get away more.", 45_000, fixed(eur(750), eur(10_000))],
  ["verhuizers", "auto", "Verhuizers", "Movers", "Particuliere en zakelijke verhuizingen, opslag.", "Private and business moves, storage.", "Iemand die binnenkort gaat verhuizen.", "Someone moving house soon.", 1_500, pct(1200)],
  // Bruiloft & events
  ["trouwlocaties", "events", "Trouwlocaties", "Wedding venues", "Locaties voor ceremonie, diner en feest.", "Venues for ceremony, dinner and party.", "Een stel dat net verloofd is.", "A couple that just got engaged.", 12_000, tiers(eur(5_000), [eur(5_000), eur(400)], [eur(15_000), eur(800)])],
  ["weddingplanners", "events", "Weddingplanners", "Wedding planners", "Volledige planning of coördinatie op de dag.", "Full planning or on-the-day coordination.", "Een stel dat geen stress wil.", "A couple that wants no stress.", 4_000, pct(1000)],
  ["trouwringen", "events", "Trouwringen & juweliers", "Wedding rings & jewellers", "Trouwringen, verlovingsringen, sieraden op maat.", "Wedding and engagement rings, custom jewellery.", "Iemand die op het punt staat aan te zoeken.", "Someone about to propose.", 2_500, pct(1000)],
  ["bruidsmode", "events", "Bruids- en feestmode", "Bridal & formal wear", "Trouwjurken, maatpakken, gala.", "Wedding dresses, tailored suits, formal wear.", "Een bruid of bruidegom op zoek naar de outfit.", "A bride or groom looking for the outfit.", 2_000, pct(1000)],
  ["cateraars", "events", "Cateraars", "Caterers", "Catering voor feesten, bruiloften en bedrijfsevents.", "Catering for parties, weddings and corporate events.", "Iemand die een feest, bruiloft of bedrijfsuitje organiseert.", "Someone organising a party, wedding or company outing.", 4_000, pct(1000)],
  ["fotografen", "events", "Fotografen & videografen", "Photographers & videographers", "Bruiloften, portretten, bedrijfsfoto's en video.", "Weddings, portraits, corporate photos and video.", "Een stel dat gaat trouwen, of een bedrijf dat nieuwe beelden nodig heeft.", "A couple getting married, or a company that needs new visuals.", 2_000, pct(1200)],
  ["djs", "events", "DJ's & live muziek", "DJs & live music", "DJ's, bands, geluid en licht.", "DJs, bands, sound and lighting.", "Iemand die een feest geeft dat niet saai mag zijn.", "Someone throwing a party that can't be boring.", 1_200, pct(1200)],
  ["feestlocaties", "events", "Feest- en vergaderlocaties", "Party & meeting venues", "Zalen voor verjaardagen, jubilea en bedrijfsevents.", "Venues for birthdays, anniversaries and corporate events.", "Iemand die iets te vieren heeft.", "Someone with something to celebrate.", 3_500, pct(1000)],
  ["partyverhuur", "events", "Partyverhuur", "Party rentals", "Tenten, meubilair, springkussens, foodtrucks.", "Tents, furniture, bouncy castles, food trucks.", "Iemand die een tuinfeest of bedrijfsdag organiseert.", "Someone organising a garden party or company day.", 1_500, pct(1200)],
  // Sport & lifestyle
  ["sportscholen", "sport", "Sportscholen", "Gyms", "Jaarabonnementen, groepslessen.", "Annual memberships, group classes.", "Iemand die wil beginnen met sporten of overstappen.", "Someone who wants to start training or switch gyms.", 600, fixed(eur(100), eur(400))],
  ["personal-trainers", "sport", "Personal trainers", "Personal trainers", "1-op-1 training, voedingsschema's, trajecten.", "1-on-1 training, nutrition plans, programmes.", "Iemand die echt resultaat wil.", "Someone who really wants results.", 1_200, pct(1500)],
  ["vechtsport", "sport", "Vechtsport & boksscholen", "Martial arts & boxing", "Boksen, kickboksen, BJJ, zelfverdediging.", "Boxing, kickboxing, BJJ, self-defence.", "Iemand die zelfvertrouwen en conditie wil.", "Someone who wants confidence and fitness.", 500, fixed(eur(75), eur(300))],
  ["schoonheidssalons", "sport", "Beauty & huidverzorging", "Beauty & skincare", "Behandeltrajecten, laserontharing, huidtherapie.", "Treatment courses, laser hair removal, skin therapy.", "Iemand die een behandeltraject overweegt.", "Someone considering a treatment course.", 1_000, pct(1500)],
  ["tattoo", "sport", "Tattoo & piercing", "Tattoo & piercing", "Custom tattoos, cover-ups, piercings.", "Custom tattoos, cover-ups, piercings.", "Iemand die al lang een tattoo wil.", "Someone who has wanted a tattoo for ages.", 600, pct(1500, 30_000, 5_000)],
  // Zakelijk & tech
  ["webdesign-marketing", "zakelijk", "Webdesign en marketing", "Web design and marketing", "Websites, webshops, online marketing.", "Websites, web shops, online marketing.", "Een ondernemer met een verouderde website.", "A business owner with an outdated website.", 5_000, pct(1200)],
  ["app-ontwikkeling", "zakelijk", "Software & apps", "Software & apps", "Apps, maatwerksoftware, koppelingen.", "Apps, custom software, integrations.", "Een bedrijf dat processen wil automatiseren.", "A company that wants to automate processes.", 20_000, tiers(eur(5_000), [eur(5_000), eur(500)], [eur(20_000), eur(1_500)], [eur(50_000), eur(3_000)])],
  ["it-support", "zakelijk", "IT-beheer & cybersecurity", "IT support & cybersecurity", "Werkplekbeheer, netwerken, back-ups, beveiliging.", "Workplace management, networks, backups, security.", "Een mkb'er die IT-gedoe zat is.", "A small business tired of IT hassle.", 6_000, pct(1000)],
  ["schoonmaakbedrijven", "zakelijk", "Kantoorschoonmaak", "Office cleaning", "Kantoorschoonmaak, glasbewassing, opleveringen.", "Office cleaning, window cleaning, end-of-project cleans.", "Een ondernemer die een schoonmaker zoekt voor zijn pand.", "A business owner looking for a cleaner for their premises.", 3_000, fixed(eur(200), eur(1_000))],
  ["drukwerk", "zakelijk", "Drukwerk & signing", "Print & signage", "Belettering, gevelreclame, drukwerk, beursmateriaal.", "Vehicle lettering, signage, print, trade-show materials.", "Een ondernemer met een nieuw pand of bedrijfsbus.", "A business with new premises or a new van.", 2_000, pct(1200)],
  ["vertalingen", "zakelijk", "Vertaalbureaus", "Translation agencies", "Vertalingen, beëdigde vertalingen, tolken.", "Translations, sworn translations, interpreting.", "Een bedrijf dat de grens over gaat.", "A company going international.", 1_500, pct(1200)],
  // Lessen & opleiding
  ["rijscholen", "leren", "Rijscholen", "Driving schools", "Rijlessen auto en motor, pakketten, spoedopleidingen.", "Car and motorcycle lessons, packages, intensive courses.", "Iemand die net 17 is geworden.", "Someone who just turned 17.", 2_200, fixed(eur(200), eur(1_000))],
  ["bijles", "leren", "Bijles & huiswerkbegeleiding", "Tutoring & homework help", "Bijles, examentraining, huiswerkinstituten.", "Tutoring, exam training, homework centres.", "Ouders van een scholier die een duwtje nodig heeft.", "Parents of a student who needs a push.", 1_200, pct(1500)],
  ["taalcursussen", "leren", "Taalcursussen", "Language courses", "Nederlands, Engels, Spaans en meer, groep of privé.", "Dutch, English, Spanish and more, group or private.", "Iemand die voor werk of liefde een taal wil leren.", "Someone learning a language for work or love.", 900, pct(1500)],
  ["muziekles", "leren", "Muziekles", "Music lessons", "Gitaar, piano, zang, drums, productie.", "Guitar, piano, singing, drums, production.", "Iemand die altijd al een instrument wilde spelen.", "Someone who always wanted to play an instrument.", 800, pct(1500)],
  ["vakopleidingen", "leren", "Cursussen & vakopleidingen", "Courses & vocational training", "Certificaten, bijscholing, bedrijfstrainingen.", "Certificates, upskilling, corporate training.", "Iemand die een volgende stap in zijn carrière wil.", "Someone ready for the next career step.", 2_500, pct(1200)],
  // Diensten aan huis
  ["schoonmaak-particulier", "diensten", "Schoonmaak aan huis", "Home cleaning", "Wekelijkse schoonmaak, voorjaarsschoonmaak, opleveringen.", "Weekly cleaning, spring cleaning, move-out cleans.", "Een druk gezin zonder tijd.", "A busy family with no time.", 1_200, fixed(eur(100), eur(500))],
  ["glazenwassers", "diensten", "Glazenwassers & gevelreiniging", "Window & facade cleaning", "Ramen, gevels, dakgoten, zonnepanelen reinigen.", "Windows, facades, gutters, solar panel cleaning.", "Iemand die al lang naar vieze ramen kijkt.", "Someone tired of dirty windows.", 600, pct(1500, 20_000, 2_500)],
  ["ongediertebestrijding", "diensten", "Ongediertebestrijding", "Pest control", "Muizen, ratten, wespen, bedwantsen.", "Mice, rats, wasps, bed bugs.", "Iemand met een plaag die snel weg moet.", "Someone with a pest that has to go fast.", 400, fixed(eur(50), eur(150))],
  ["slotenmakers", "diensten", "Slotenmakers", "Locksmiths", "Sloten vervangen, inbraakpreventie, buitengesloten.", "Lock replacement, burglary prevention, lockouts.", "Iemand die net is verhuisd of buitengesloten.", "Someone who just moved or is locked out.", 400, fixed(eur(50), eur(150))],
  ["dierenverzorging", "diensten", "Dierenverzorging", "Pet care", "Trimsalons, uitlaatservice, dierenoppas.", "Grooming, dog walking, pet sitting.", "Iemand met een hond en weinig tijd.", "Someone with a dog and little time.", 600, pct(1500, 20_000, 2_500)],

  // Uitbreiding: allerlei bedrijven
  ["schuifdeuren", "wonen", "Binnendeuren & schuifdeuren", "Interior & sliding doors", "Binnendeuren, taatsdeuren, glazen schuifwanden.", "Interior doors, pivot doors, glass sliding walls.", "Iemand die zijn interieur wil opfrissen.", "Someone refreshing their interior.", 3000, pct(1000)],
  ["trappen", "wonen", "Trappen & traprenovatie", "Stairs & stair renovation", "Nieuwe trappen en traprenovatie met PVC, hout of beton.", "New stairs and renovation in vinyl, wood or concrete.", "Iemand met een versleten trap.", "Someone with a worn staircase.", 3500, pct(1000)],
  ["vloerverwarming", "wonen", "Vloerverwarming", "Underfloor heating", "Infrezen of aanleggen van vloerverwarming.", "Milling in or laying underfloor heating.", "Iemand die een nieuwe vloer laat leggen.", "Someone getting a new floor.", 3500, pct(1000)],
  ["gevelrenovatie", "wonen", "Gevelrenovatie & voegwerk", "Facade renovation & pointing", "Voegen, gevelreiniging, impregneren, gevelbekleding.", "Pointing, facade cleaning, impregnation, cladding.", "Iemand met een vervuilde of verweerde gevel.", "Someone with a dirty or weathered facade.", 6000, pct(800)],
  ["asbestsanering", "wonen", "Asbestsanering", "Asbestos removal", "Inventarisatie en verwijdering door gecertificeerde saneerders.", "Survey and removal by certified contractors.", "Iemand met een oude schuur of een asbestdak.", "Someone with an old shed or asbestos roof.", 5000, pct(800)],
  ["sloopwerk", "wonen", "Sloop & strippen", "Demolition & strip-outs", "Sloopwerk binnen en buiten, afvoer van puin.", "Interior and exterior demolition, rubble removal.", "Iemand die een verbouwing begint.", "Someone starting a renovation.", 4000, pct(1000)],
  ["funderingsherstel", "wonen", "Funderingsherstel", "Foundation repair", "Funderingsonderzoek en -herstel, kelderafdichting.", "Foundation surveys and repair, basement sealing.", "Iemand met scheuren in de muren of een verzakkend huis.", "Someone with cracked walls or a sinking house.", 30000, tiers(eur(5_000), [eur(5_000), eur(500)], [eur(25_000), eur(1_500)])],
  ["schoorsteen", "wonen", "Haarden & schoorstenen", "Fireplaces & chimneys", "Houtkachels, gashaarden, schoorsteenvegen.", "Wood stoves, gas fires, chimney sweeping.", "Iemand die van een haard droomt.", "Someone dreaming of a fireplace.", 4500, pct(1000)],
  ["meubelmakers", "wonen", "Meubelmakers", "Furniture makers", "Tafels, kasten en meubels op maat.", "Custom tables, cabinets and furniture.", "Iemand die iets unieks wil.", "Someone who wants something unique.", 3000, pct(1000)],
  ["stoffeerders", "wonen", "Stoffeerders", "Upholsterers", "Bankstellen en stoelen opnieuw bekleden.", "Reupholstering sofas and chairs.", "Iemand met een geliefde maar versleten bank.", "Someone with a loved but worn sofa.", 1200, pct(1200)],
  ["interieurontwerp", "wonen", "Interieurontwerp & styling", "Interior design & styling", "Interieurplannen, kleuradvies, styling.", "Interior plans, colour advice, styling.", "Iemand die net een huis kocht.", "Someone who just bought a home.", 2500, pct(1200)],
  ["verlichting", "wonen", "Verlichting & lichtplannen", "Lighting & lighting plans", "Lichtplannen, design-armaturen, montage.", "Lighting plans, designer fixtures, fitting.", "Iemand die gaat verbouwen.", "Someone renovating.", 2000, pct(1000)],
  ["kluswerk", "wonen", "Klusbedrijven", "Handyman services", "Kleine klussen, montage, reparaties in en om huis.", "Small jobs, assembly, repairs around the house.", "Iemand met een lijst klussen waar hij niet aan toe komt.", "Someone with a to-do list they never get to.", 800, pct(1200)],
  ["vochtbestrijding", "wonen", "Vochtbestrijding", "Damp proofing", "Optrekkend vocht, schimmel, kelderafdichting.", "Rising damp, mould, basement sealing.", "Iemand met schimmel of een vochtige kelder.", "Someone with mould or a damp basement.", 3000, pct(1000)],
  ["ventilatie", "energie", "Ventilatie & WTW", "Ventilation & heat recovery", "Mechanische ventilatie, WTW-units, onderhoud.", "Mechanical ventilation, heat-recovery units, servicing.", "Iemand met een benauwd of vochtig huis.", "Someone with a stuffy or damp house.", 3500, pct(1000)],
  ["energieadvies", "energie", "Energielabel & advies", "Energy labels & advice", "Energielabels, maatwerkadvies, subsidieaanvragen.", "Energy labels, tailored advice, grant applications.", "Iemand die zijn huis gaat verkopen of verduurzamen.", "Someone selling or making their home greener.", 400, fixed(eur(60), eur(0))],
  ["zonneboilers", "energie", "Zonneboilers", "Solar water heaters", "Warm water uit zonne-energie.", "Hot water from solar energy.", "Iemand die zijn gasverbruik wil verlagen.", "Someone wanting to cut gas use.", 4000, fixed(eur(300), eur(1500))],
  ["bedrijfsdaken-zon", "energie", "Zonnepanelen voor bedrijven", "Commercial solar", "Grote daken, boerderijen, bedrijfspanden.", "Large roofs, farms, commercial buildings.", "Een ondernemer met een groot dak.", "A business owner with a big roof.", 60000, tiers(eur(15_000), [eur(15_000), eur(1_000)], [eur(50_000), eur(2_500)], [eur(150_000), eur(5_000)])],
  ["tuinhuizen", "buiten", "Tuinhuizen & blokhutten", "Garden sheds & cabins", "Tuinhuizen, blokhutten, tuinkantoren.", "Garden sheds, log cabins, garden offices.", "Iemand die thuis wil werken in de tuin.", "Someone who wants a garden office.", 5000, pct(1000)],
  ["kunstgras", "buiten", "Kunstgras & sportvelden", "Artificial grass", "Kunstgras voor tuin, speelplaats en balkon.", "Artificial grass for gardens, playgrounds and balconies.", "Iemand die geen zin heeft in maaien.", "Someone tired of mowing.", 3000, pct(1000)],
  ["vijvers", "buiten", "Vijvers & waterpartijen", "Ponds & water features", "Vijveraanleg, filters, fonteinen.", "Pond construction, filters, fountains.", "Iemand die rust in zijn tuin wil.", "Someone wanting calm in their garden.", 4000, pct(1000)],
  ["buitenkeukens", "buiten", "Buitenkeukens & BBQ", "Outdoor kitchens & BBQ", "Buitenkeukens, kamado's, pizzaovens.", "Outdoor kitchens, kamados, pizza ovens.", "Iemand die graag buiten kookt.", "Someone who loves cooking outside.", 6000, pct(1000)],
  ["tuinverlichting", "buiten", "Tuinverlichting", "Garden lighting", "Sfeerverlichting, grondspots, slimme aansturing.", "Mood lighting, ground spots, smart control.", "Iemand met een nieuwe tuin.", "Someone with a new garden.", 1500, pct(1200)],
  ["tuinonderhoud", "buiten", "Tuinonderhoud", "Garden maintenance", "Vaste onderhoudscontracten, snoeien, onkruid.", "Maintenance contracts, pruning, weeding.", "Iemand met een tuin en weinig tijd.", "Someone with a garden and little time.", 1200, pct(1200)],
  ["hekwerk-bedrijf", "buiten", "Bedrijfshekwerk & poorten", "Commercial fencing & gates", "Hekwerk, slagbomen en poorten voor bedrijven.", "Fencing, barriers and gates for businesses.", "Een ondernemer met een bedrijfsterrein.", "A business owner with a yard.", 12000, pct(600)],
  ["motoren", "auto", "Motoren & motorkleding", "Motorcycles & gear", "Nieuwe en gebruikte motoren, kleding, onderhoud.", "New and used motorcycles, gear, servicing.", "Iemand die net zijn motorrijbewijs heeft.", "Someone who just got their motorcycle licence.", 9000, fixed(eur(250), eur(2000))],
  ["bandenservice", "auto", "Banden & velgen", "Tyres & wheels", "Zomer-, winter- en all-seasonbanden, velgen.", "Summer, winter and all-season tyres, wheels.", "Iemand met versleten banden.", "Someone with worn tyres.", 600, fixed(eur(40), eur(300))],
  ["autoverhuur", "auto", "Auto- en busverhuur", "Car & van rental", "Personenauto's, busjes, verhuiswagens.", "Cars, vans, moving trucks.", "Iemand die gaat verhuizen of op vakantie gaat.", "Someone moving or going on holiday.", 400, fixed(eur(40), eur(150))],
  ["bedrijfswagens", "auto", "Bedrijfswagens", "Commercial vehicles", "Bestelbussen, inrichting en belettering.", "Vans, fit-outs and lettering.", "Een ondernemer die een bus nodig heeft.", "A business owner who needs a van.", 30000, fixed(eur(500), eur(5000))],
  ["autoruiten", "auto", "Autoruitherstel", "Windscreen repair", "Sterretjes repareren, ruiten vervangen.", "Chip repairs, windscreen replacement.", "Iemand met een ster in de ruit.", "Someone with a chip in their windscreen.", 400, fixed(eur(30), eur(100))],
  ["fietsenwinkels", "auto", "Fietsenwinkels", "Bike shops", "Stadsfietsen, racefietsen, bakfietsen, onderhoud.", "City bikes, road bikes, cargo bikes, servicing.", "Iemand wiens fiets gestolen is.", "Someone whose bike was stolen.", 1500, pct(1000)],
  ["taxi", "auto", "Taxi & personenvervoer", "Taxi & chauffeur services", "Luchthavenvervoer, groepsvervoer, trouwauto's.", "Airport transfers, group transport, wedding cars.", "Iemand die naar Schiphol moet.", "Someone heading to the airport.", 250, pct(1200)],
  ["fotobooth", "events", "Fotobooths & selfiespiegels", "Photo booths", "Fotobooths en selfiespiegels voor feesten.", "Photo booths and selfie mirrors for parties.", "Iemand die een feest geeft.", "Someone throwing a party.", 500, fixed(eur(60), eur(0))],
  ["foodtrucks", "events", "Foodtrucks", "Food trucks", "Foodtrucks voor feesten en bedrijfsevents.", "Food trucks for parties and corporate events.", "Iemand die een feest of bedrijfsdag organiseert.", "Someone organising a party or company day.", 1500, pct(1000)],
  ["bloemisten", "events", "Bloemisten & bruidsboeketten", "Florists", "Bloemwerk voor bruiloften, events en bedrijven.", "Floral design for weddings, events and businesses.", "Iemand die gaat trouwen.", "Someone getting married.", 1200, pct(1000)],
  ["taarten", "events", "Taarten & patisserie", "Cakes & patisserie", "Bruidstaarten, verjaardagstaarten, sweet tables.", "Wedding cakes, birthday cakes, sweet tables.", "Iemand die een feest plant.", "Someone planning a party.", 600, pct(1200)],
  ["kinderfeestjes", "events", "Kinderfeestjes", "Kids' parties", "Kinderfeest-locaties en -animatie.", "Kids' party venues and entertainers.", "Een ouder met een jarig kind.", "A parent with a birthday coming up.", 350, fixed(eur(40), eur(0))],
  ["bedrijfsuitjes", "events", "Bedrijfsuitjes & teambuilding", "Company outings", "Uitjes, workshops, teambuilding, escape rooms.", "Outings, workshops, team building, escape rooms.", "Iemand die het personeelsuitje regelt.", "Someone organising the staff outing.", 3000, pct(1000)],
  ["evenementenbureaus", "events", "Evenementenbureaus", "Event agencies", "Organisatie van congressen, festivals, beurzen.", "Organising conferences, festivals, trade fairs.", "Een bedrijf dat een event wil.", "A company planning an event.", 15000, pct(600)],
  ["geluid-licht", "events", "Geluid, licht & podium", "Sound, lighting & staging", "Verhuur en techniek voor events.", "Rental and crew for events.", "Iemand die een event organiseert.", "Someone organising an event.", 2500, pct(1000)],
  ["yoga", "sport", "Yoga & pilates", "Yoga & pilates", "Studio's, rittenkaarten, privélessen.", "Studios, class passes, private lessons.", "Iemand die wil ontspannen of sterker wil worden.", "Someone wanting to relax or get stronger.", 600, fixed(eur(50), eur(0))],
  ["crossfit", "sport", "CrossFit & bootcamps", "CrossFit & bootcamps", "Boxen, bootcamps, outdoor training.", "Boxes, bootcamps, outdoor training.", "Iemand die wil afvallen met een groep.", "Someone wanting to lose weight in a group.", 700, fixed(eur(60), eur(0))],
  ["kappers", "sport", "Kappers & barbiers", "Hairdressers & barbers", "Kappers, barbershops, bruidskapsels.", "Hairdressers, barbershops, bridal hair.", "Iemand die een nieuwe kapper zoekt.", "Someone looking for a new hairdresser.", 300, fixed(eur(25), eur(0))],
  ["nagelstudios", "sport", "Nagelstudio's & wimpers", "Nail & lash studios", "Nagels, wimperextensions, brows.", "Nails, lash extensions, brows.", "Iemand die regelmatig haar nagels laat doen.", "Someone who regularly gets their nails done.", 250, fixed(eur(20), eur(0))],
  ["sauna", "sport", "Sauna & wellness", "Spas & saunas", "Dagjes wellness, arrangementen, cadeaubonnen.", "Spa days, packages, gift cards.", "Iemand die een cadeau zoekt.", "Someone looking for a gift.", 300, fixed(eur(25), eur(0))],
  ["golf", "sport", "Golf & golfles", "Golf & lessons", "Golfbaanpermissie, lessen, lidmaatschappen.", "Golf licence courses, lessons, memberships.", "Iemand die wil leren golfen.", "Someone wanting to learn golf.", 1200, pct(1000)],
  ["dansscholen", "sport", "Dansscholen", "Dance schools", "Stijldansen, streetdance, openingsdans.", "Ballroom, street dance, first dance lessons.", "Een stel dat gaat trouwen.", "A couple getting married.", 400, fixed(eur(40), eur(0))],
  ["zwemles", "sport", "Zwemles", "Swimming lessons", "Zwemdiploma's A/B/C, volwassenenzwemles.", "Swimming certificates, adult lessons.", "Een ouder met een kind van vijf.", "A parent with a five-year-old.", 500, fixed(eur(40), eur(0))],
  ["di\u00ebtisten-coaching", "sport", "Leefstijl- & voedingscoaches", "Lifestyle & nutrition coaches", "Voedingsschema's, leefstijltrajecten (geen medische zorg).", "Meal plans, lifestyle programmes (not medical care).", "Iemand die gezonder wil leven.", "Someone wanting to live healthier.", 600, pct(1200)],
  ["boekhouders", "zakelijk", "Boekhouders & administratie", "Bookkeepers", "Boekhouding, btw-aangifte, salarisadministratie.", "Bookkeeping, VAT returns, payroll.", "Een zzp'er die geen zin heeft in administratie.", "A freelancer who hates admin.", 2000, pct(1000)],
  ["seo", "zakelijk", "SEO & Google Ads", "SEO & Google Ads", "Vindbaarheid, advertenties, analytics.", "Search visibility, ads, analytics.", "Een ondernemer die meer klanten online wil.", "A business owner who wants more customers online.", 3000, pct(1000)],
  ["social-media", "zakelijk", "Social media & content", "Social media & content", "Contentcreatie, TikTok, Instagram, influencers.", "Content creation, TikTok, Instagram, influencers.", "Een bedrijf dat niet weet wat het moet posten.", "A business that doesn't know what to post.", 2500, pct(1000)],
  ["videoproductie", "zakelijk", "Videoproductie", "Video production", "Bedrijfsfilms, commercials, animatie.", "Corporate films, commercials, animation.", "Een bedrijf dat een video nodig heeft.", "A company that needs a video.", 4000, pct(1000)],
  ["branding", "zakelijk", "Branding & logo-ontwerp", "Branding & logo design", "Logo's, huisstijlen, verpakkingen.", "Logos, brand identities, packaging.", "Iemand die een bedrijf start.", "Someone starting a business.", 2500, pct(1000)],
  ["webshops", "zakelijk", "Webshopbouwers", "E-commerce builders", "Shopify, WooCommerce, koppelingen met marketplaces.", "Shopify, WooCommerce, marketplace integrations.", "Een winkel die online wil verkopen.", "A shop that wants to sell online.", 5000, pct(1000)],
  ["telefonie", "zakelijk", "Zakelijke telefonie & internet", "Business phone & internet", "VoIP, glasvezel, mobiele abonnementen voor bedrijven.", "VoIP, fibre, business mobile plans.", "Een bedrijf met een duur of traag abonnement.", "A business with an expensive or slow plan.", 2000, fixed(eur(150), eur(500))],
  ["kantoorinrichting", "zakelijk", "Kantoorinrichting", "Office furniture & fit-out", "Bureaus, stoelen, akoestiek, complete inrichting.", "Desks, chairs, acoustics, full fit-outs.", "Een bedrijf dat verhuist of groeit.", "A company moving or growing.", 10000, pct(800)],
  ["koffieautomaten", "zakelijk", "Koffie op kantoor", "Office coffee", "Koffiemachines, bonen, onderhoud voor bedrijven.", "Coffee machines, beans, servicing for offices.", "Een kantoor met slechte koffie.", "An office with bad coffee.", 3000, fixed(eur(200), eur(1000))],
  ["bedrijfskleding", "zakelijk", "Bedrijfskleding & merchandise", "Workwear & merchandise", "Bedrukte kleding, werkkleding, relatiegeschenken.", "Printed clothing, workwear, promotional gifts.", "Een team zonder eigen kleding.", "A team without its own clothing.", 2500, pct(1000)],
  ["beveiliging-bedrijf", "zakelijk", "Bedrijfsbeveiliging", "Business security", "Camerabewaking, toegangscontrole, alarmopvolging.", "CCTV, access control, alarm response.", "Een ondernemer na een inbraak.", "A business owner after a break-in.", 5000, pct(800)],
  ["uitzendbureaus", "zakelijk", "Werving & selectie", "Recruitment", "Werving, detachering, headhunting.", "Recruitment, secondment, headhunting.", "Een bedrijf dat mensen zoekt.", "A company looking for staff.", 6000, pct(1000)],
  ["vergaderruimtes", "zakelijk", "Flexplekken & vergaderruimtes", "Coworking & meeting rooms", "Flexplekken, kantoorruimte, vergaderzalen.", "Coworking desks, offices, meeting rooms.", "Een zzp'er die niet meer thuis wil werken.", "A freelancer tired of working from home.", 3000, fixed(eur(150), eur(0))],
  ["ai-automatisering", "zakelijk", "AI & automatisering", "AI & automation", "Chatbots, procesautomatisering, data-koppelingen.", "Chatbots, process automation, data integrations.", "Een bedrijf dat tijd verliest aan handwerk.", "A company losing time to manual work.", 8000, pct(1000)],
  ["drones", "zakelijk", "Drone-opnames & inspecties", "Drone footage & inspections", "Luchtfoto's, inspecties van daken en panden.", "Aerial photos, roof and building inspections.", "Een makelaar of aannemer die beelden nodig heeft.", "An agent or contractor who needs footage.", 800, pct(1200)],
  ["bedrijfsschoonmaak-industrie", "zakelijk", "Industriële reiniging", "Industrial cleaning", "Reiniging van hallen, machines, graffiti.", "Cleaning halls, machines, graffiti removal.", "Een bedrijf met een vervuilde hal.", "A company with a dirty warehouse.", 6000, pct(800)],
  ["afvalverwerking", "zakelijk", "Containers & afvalafvoer", "Skips & waste removal", "Containerhuur, puinafvoer, bedrijfsafval.", "Skip hire, rubble removal, commercial waste.", "Iemand die gaat verbouwen of opruimen.", "Someone renovating or clearing out.", 400, fixed(eur(30), eur(0))],
  ["rijscholen-motor", "leren", "Motorrijscholen", "Motorcycle schools", "Motorrijlessen A1, A2 en A.", "Motorcycle lessons A1, A2 and A.", "Iemand die zijn motorrijbewijs wil halen.", "Someone wanting a motorcycle licence.", 1800, fixed(eur(150), eur(600))],
  ["vaarbewijs", "leren", "Vaarbewijs & zeilles", "Boating licence & sailing", "Vaarbewijs, zeilles, sloepcursus.", "Boating licence, sailing lessons, boat courses.", "Iemand met plannen voor een boot.", "Someone planning to get a boat.", 600, fixed(eur(50), eur(0))],
  ["programmeren", "leren", "Programmeer- & IT-cursussen", "Coding & IT courses", "Bootcamps, certificeringen, omscholing naar IT.", "Bootcamps, certifications, retraining into IT.", "Iemand die wil switchen naar IT.", "Someone switching to IT.", 4000, pct(1000)],
  ["kookles", "leren", "Kookworkshops", "Cooking classes", "Kookcursussen en workshops, ook voor groepen.", "Cooking courses and workshops, also for groups.", "Iemand die een uitje of cadeau zoekt.", "Someone looking for an outing or gift.", 400, fixed(eur(30), eur(0))],
  ["examentraining", "leren", "Examentraining & studiebegeleiding", "Exam training", "Examentraining VMBO, HAVO, VWO.", "Exam prep for secondary school.", "Een ouder met een kind in het examenjaar.", "A parent with a child in their exam year.", 700, fixed(eur(60), eur(0))],
  ["kunstles", "leren", "Teken- & kunstles", "Art classes", "Tekenen, schilderen, keramiek, fotografie.", "Drawing, painting, ceramics, photography.", "Iemand die een creatieve hobby zoekt.", "Someone looking for a creative hobby.", 400, fixed(eur(30), eur(0))],
  ["vliegles", "leren", "Vliegles & proeflessen", "Flying lessons", "Proefvluchten, brevetopleidingen.", "Trial flights, pilot training.", "Iemand die altijd al wilde vliegen.", "Someone who always wanted to fly.", 300, fixed(eur(30), eur(0))],
  ["opruimen", "diensten", "Ontruimingen & opruimcoaches", "House clearances & decluttering", "Woningontruiming, opruimcoaching, opslag.", "House clearances, decluttering, storage.", "Iemand die een ouderlijk huis moet leeghalen.", "Someone clearing a parent's home.", 1500, pct(1000)],
  ["opslag", "diensten", "Self storage", "Self storage", "Opslagboxen per maand.", "Monthly storage units.", "Iemand tussen twee huizen in.", "Someone between homes.", 600, fixed(eur(50), eur(0))],
  ["witgoed", "diensten", "Witgoed reparatie", "Appliance repair", "Wasmachines, drogers, vaatwassers repareren.", "Repairing washing machines, dryers, dishwashers.", "Iemand met een kapotte wasmachine.", "Someone with a broken washing machine.", 200, fixed(eur(15), eur(0))],
  ["telefoonreparatie", "diensten", "Telefoon- & laptopreparatie", "Phone & laptop repair", "Schermen, accu's, dataherstel.", "Screens, batteries, data recovery.", "Iemand met een gebarsten scherm.", "Someone with a cracked screen.", 200, fixed(eur(15), eur(0))],
  ["kleermakers", "diensten", "Kleermakers & stomerijen", "Tailors & dry cleaners", "Vermaken, maatwerk, stomen.", "Alterations, tailoring, dry cleaning.", "Iemand met een pak dat niet past.", "Someone with a suit that doesn't fit.", 250, fixed(eur(20), eur(0))],
  ["hondenscholen", "diensten", "Hondenscholen & -trainers", "Dog training", "Puppycursussen, gedragstraining.", "Puppy courses, behaviour training.", "Iemand met een nieuwe pup.", "Someone with a new puppy.", 300, fixed(eur(25), eur(0))],
  ["dierenpensions", "diensten", "Dierenpensions", "Pet boarding", "Pensions voor honden en katten.", "Kennels and catteries.", "Iemand die op vakantie gaat met een huisdier thuis.", "Someone going on holiday with a pet at home.", 400, fixed(eur(30), eur(0))],
  ["ouderenservice", "diensten", "Hulp voor ouderen (niet-medisch)", "Help for the elderly (non-medical)", "Boodschappen, gezelschap, klusjes, alarmering.", "Shopping, companionship, odd jobs, alarm services.", "Iemand met ouders die hulp kunnen gebruiken.", "Someone whose parents could use help.", 1200, pct(1000)],
  ["rouw", "diensten", "Grafmonumenten", "Headstones & memorials", "Grafstenen, gedenktekens, onderhoud.", "Headstones, memorials, maintenance.", "Een familie die een gedenkteken zoekt.", "A family looking for a memorial.", 3000, pct(800)],
  ["klokkenreparatie", "diensten", "Horloge- & sieradenreparatie", "Watch & jewellery repair", "Horloges, sieraden, graveren.", "Watches, jewellery, engraving.", "Iemand met een kapot horloge.", "Someone with a broken watch.", 250, fixed(eur(20), eur(0))],
  ["meubelzaken", "winkels", "Meubelzaken", "Furniture stores", "Banken, eettafels, slaapkamers.", "Sofas, dining tables, bedrooms.", "Iemand die net verhuisd is.", "Someone who just moved.", 3000, pct(800)],
  ["matrassen", "winkels", "Bedden & matrassen", "Beds & mattresses", "Boxsprings, matrassen, slaapadvies.", "Box springs, mattresses, sleep advice.", "Iemand die slecht slaapt.", "Someone who sleeps badly.", 2000, pct(800)],
  ["opticiens", "winkels", "Opticiens", "Opticians", "Brillen, zonnebrillen, lenzen.", "Glasses, sunglasses, contact lenses.", "Iemand die een nieuwe bril nodig heeft.", "Someone who needs new glasses.", 500, fixed(eur(40), eur(0))],
  ["hoortoestellen", "winkels", "Hoortoestellen", "Hearing aids", "Hoortoestellen en gehoorbescherming.", "Hearing aids and hearing protection.", "Iemand die steeds 'wat zeg je?' zegt.", "Someone always saying 'pardon?'.", 2500, fixed(eur(150), eur(0))],
  ["elektronica", "winkels", "Elektronica & audio", "Electronics & audio", "Tv's, hifi, home cinema, installatie.", "TVs, hi-fi, home cinema, installation.", "Iemand die een home cinema wil.", "Someone who wants a home cinema.", 2000, pct(800)],
  ["witgoedwinkels", "winkels", "Witgoed & keukenapparatuur", "Appliances", "Wasmachines, koelkasten, inbouwapparatuur.", "Washing machines, fridges, built-in appliances.", "Iemand met een kapotte koelkast.", "Someone with a broken fridge.", 900, fixed(eur(50), eur(0))],
  ["juweliers", "winkels", "Juweliers & horloges", "Jewellers & watches", "Horloges, sieraden, op maat gemaakt.", "Watches, jewellery, made to order.", "Iemand die een cadeau zoekt.", "Someone looking for a gift.", 1500, pct(800)],
  ["modezaken", "winkels", "Mode & maatkleding", "Fashion & tailoring", "Maatpakken, kledingadvies, personal shopping.", "Tailored suits, style advice, personal shopping.", "Iemand die een pak zoekt.", "Someone looking for a suit.", 800, pct(1000)],
  ["sportwinkels", "winkels", "Sportwinkels", "Sports shops", "Hardloopschoenen, fietskleding, ski-uitrusting.", "Running shoes, cycling kit, ski gear.", "Iemand die gaat sporten.", "Someone taking up a sport.", 400, fixed(eur(25), eur(0))],
  ["gaming", "winkels", "Gaming & pc-bouwers", "Gaming & PC builders", "Game-pc's op maat, consoles, accessoires.", "Custom gaming PCs, consoles, accessories.", "Iemand die een nieuwe game-pc wil.", "Someone who wants a new gaming PC.", 2000, pct(800)],
  ["tuincentra", "winkels", "Tuincentra & planten", "Garden centres & plants", "Planten, potten, tuinmeubels.", "Plants, pots, garden furniture.", "Iemand met een nieuwe tuin of balkon.", "Someone with a new garden or balcony.", 800, pct(800)],
  ["dierenwinkels", "winkels", "Dierenwinkels", "Pet shops", "Voer, verblijven, aquaria.", "Food, enclosures, aquariums.", "Iemand met een nieuw huisdier.", "Someone with a new pet.", 300, fixed(eur(20), eur(0))],
  ["babywinkels", "winkels", "Babywinkels", "Baby stores", "Kinderwagens, babykamers, autostoeltjes.", "Prams, nurseries, car seats.", "Iemand die zwanger is.", "Someone expecting a baby.", 1500, pct(800)],
  ["muziekwinkels", "winkels", "Muziekinstrumenten", "Music shops", "Gitaren, piano's, studio-apparatuur.", "Guitars, pianos, studio gear.", "Iemand die een instrument wil leren spelen.", "Someone wanting to learn an instrument.", 1000, pct(800)],
  ["vloerkleden", "winkels", "Vloerkleden & tapijt", "Rugs & carpet", "Vloerkleden en tapijt op maat.", "Rugs and fitted carpet.", "Iemand die zijn kamer wil opfrissen.", "Someone refreshing a room.", 1000, pct(1000)],
  ["restaurants", "horeca", "Restaurants & groepsdiners", "Restaurants & group dinners", "Groepsreserveringen, besloten diners, arrangementen.", "Group bookings, private dinners, packages.", "Iemand die een etentje voor een groep regelt.", "Someone booking dinner for a group.", 800, pct(800)],
  ["lunchroom-catering", "horeca", "Bedrijfslunches & catering", "Office lunches & catering", "Lunchbezorging en catering voor kantoren.", "Lunch delivery and catering for offices.", "Een kantoor zonder kantine.", "An office without a canteen.", 2000, pct(1000)],
  ["bakkers", "horeca", "Bakkers & traiteurs", "Bakers & delis", "Bestellingen voor feesten, kantoor en bruiloften.", "Orders for parties, offices and weddings.", "Iemand die een feest geeft.", "Someone throwing a party.", 300, fixed(eur(20), eur(0))],
  ["wijnhandels", "horeca", "Wijn & drank voor events", "Wine & drinks for events", "Wijnen, bieren en drankpakketten.", "Wines, beers and drinks packages.", "Iemand die een feest of bruiloft geeft.", "Someone throwing a party or wedding.", 800, pct(800)],
  ["barista", "horeca", "Koffiebar & mobiele bar", "Mobile bars & baristas", "Mobiele bars, cocktails en barista's op locatie.", "Mobile bars, cocktails and baristas on site.", "Iemand die een event organiseert.", "Someone organising an event.", 1200, pct(1000)],
  ["chefs", "horeca", "Privé-chefs", "Private chefs", "Chef aan huis voor diners en feesten.", "Chef at home for dinners and parties.", "Iemand die thuis een bijzonder diner wil.", "Someone wanting a special dinner at home.", 900, pct(1000)],
  ["horeca-inrichting", "horeca", "Horeca-inrichting", "Restaurant fit-out", "Keukens, meubilair en inrichting voor horeca.", "Kitchens, furniture and fit-out for hospitality.", "Een ondernemer die een zaak opent.", "An entrepreneur opening a venue.", 40000, tiers(eur(10_000), [eur(10_000), eur(750)], [eur(40_000), eur(2_000)])],
  ["reisbureaus", "reizen", "Reisbureaus & groepsreizen", "Travel agencies & group trips", "Groepsreizen, huwelijksreizen, maatwerkreizen.", "Group trips, honeymoons, tailor-made travel.", "Iemand die een huwelijksreis plant.", "Someone planning a honeymoon.", 4000, pct(500)],
  ["vakantieparken", "reizen", "Vakantieparken & groepsaccommodaties", "Holiday parks & group stays", "Vakantiehuizen en groepsaccommodaties.", "Holiday homes and group accommodation.", "Iemand die een weekend weg met vrienden plant.", "Someone planning a weekend away with friends.", 1500, pct(800)],
  ["bootverhuur", "reizen", "Bootverhuur & rondvaarten", "Boat rental & cruises", "Sloepen, rondvaarten, zeilschepen.", "Boats, canal cruises, sailing ships.", "Iemand die een uitje organiseert.", "Someone organising an outing.", 600, fixed(eur(50), eur(0))],
  ["escaperooms", "reizen", "Escape rooms & activiteiten", "Escape rooms & activities", "Escape rooms, karten, lasergamen, bowlen.", "Escape rooms, karting, laser tag, bowling.", "Iemand die een vrijgezellenfeest regelt.", "Someone planning a stag or hen party.", 400, fixed(eur(30), eur(0))],
  ["vrijgezellen", "reizen", "Vrijgezellenfeesten", "Stag & hen parties", "Complete vrijgezellenarrangementen.", "Complete stag and hen packages.", "Een getuige die alles moet regelen.", "A best man or maid of honour.", 1200, pct(1000)],
  ["hotels", "reizen", "Hotels & groepsovernachtingen", "Hotels & group stays", "Hotelkamers voor bruiloften, teams en events.", "Hotel rooms for weddings, teams and events.", "Iemand die gasten moet onderbrengen.", "Someone who needs to house guests.", 1500, pct(800)],
  ["ski", "reizen", "Wintersport & skireizen", "Ski trips", "Skireizen, groepsreizen, skiles.", "Ski trips, group travel, ski lessons.", "Een vriendengroep die op wintersport wil.", "A group of friends planning a ski trip.", 3000, pct(500)],
];

export const CATEGORIES: CategoryDef[] = ROWS.map(([slug, group, nameNl, nameEn, descriptionNl, descriptionEn, whoNl, whoEn, jobEur, example]) => ({
  slug, group, nameNl, nameEn, descriptionNl, descriptionEn, whoNl, whoEn, exampleJobCents: jobEur * 100, example,
}));

export const EXCLUDED_CATEGORIES = [
  { slug: "makelaardij", nameNl: "Makelaardij", nameEn: "Real estate brokerage", reasonNl: "Bemiddeling bij woningen kent eigen regels over provisies en belangenverstrengeling.", reasonEn: "Property brokerage has its own rules on commissions and conflicts of interest." },
  { slug: "hypotheken", nameNl: "Hypotheken", nameEn: "Mortgages", reasonNl: "Financieel advies en bemiddeling vallen onder de Wft en het provisieverbod.", reasonEn: "Financial advice and brokerage fall under the Dutch Wft and its commission ban." },
  { slug: "verzekeringen", nameNl: "Verzekeringen", nameEn: "Insurance", reasonNl: "Aanbrengen van verzekeringen is vergunningsplichtig bemiddelen onder de Wft.", reasonEn: "Introducing insurance counts as regulated intermediation under the Wft." },
  { slug: "financiele-producten", nameNl: "Overige financiële producten", nameEn: "Other financial products", reasonNl: "Leningen, beleggingen en vergelijkbare producten vallen onder financieel toezicht.", reasonEn: "Loans, investments and similar products are under financial supervision." },
  { slug: "advocatuur", nameNl: "Advocatuur", nameEn: "Legal services", reasonNl: "Advocaten mogen geen vergoeding betalen voor het aanbrengen van cliënten.", reasonEn: "Lawyers may not pay fees for introducing clients." },
  { slug: "medische-zorg", nameNl: "Medische zorg", nameEn: "Medical care", reasonNl: "Betaald doorverwijzen naar zorgverleners is onwenselijk en deels verboden.", reasonEn: "Paid referral to healthcare providers is undesirable and partly prohibited." },
];
