import type { FeeRule } from "@/lib/fees";

/**
 * Launch categories. `example` is a worked example used on marketing pages: a typical job amount
 * and a plausible fee rule. It is labelled as an example everywhere; real fees come from campaigns.
 */
export interface CategoryDef {
  slug: string;
  nameNl: string;
  nameEn: string;
  descriptionNl: string;
  descriptionEn: string;
  whoNl: string;
  whoEn: string;
  exampleJobCents: number;
  example: FeeRule;
}

const pct = (bps: number, minJob = 50_000, minFee = 5_000): FeeRule => ({ feeType: "PERCENTAGE", feePercentBps: bps, minJobAmountCents: minJob, minFeeCents: minFee });
const fixed = (cents: number, minJob = 0): FeeRule => ({ feeType: "FIXED", feeFixedCents: cents, minJobAmountCents: minJob, minFeeCents: 0 });

export const CATEGORIES: CategoryDef[] = [
  { slug: "schilders", nameNl: "Schilders", nameEn: "Painters", descriptionNl: "Binnen- en buitenschilderwerk, kozijnen, houtrot.", descriptionEn: "Interior and exterior painting, window frames, wood rot.", whoNl: "Iemand wiens kozijnen bladderen, of die net een huis heeft gekocht.", whoEn: "Someone whose window frames are peeling, or who just bought a house.", exampleJobCents: 500_000, example: pct(800) },
  { slug: "stukadoors", nameNl: "Stukadoors", nameEn: "Plasterers", descriptionNl: "Wanden en plafonds stucen, spackspuiten, sierpleister.", descriptionEn: "Plastering walls and ceilings, spray finishes, decorative plaster.", whoNl: "Iemand die gaat verbouwen of een oud huis opknapt.", whoEn: "Someone renovating or doing up an old house.", exampleJobCents: 300_000, example: pct(800) },
  { slug: "loodgieters", nameNl: "Loodgieters", nameEn: "Plumbers", descriptionNl: "Leidingwerk, afvoer, lekkages, sanitair.", descriptionEn: "Pipework, drains, leaks, sanitary fittings.", whoNl: "Iemand met een lekkage, een verstopte afvoer of een nieuwe aansluiting.", whoEn: "Someone with a leak, a blocked drain or a new connection.", exampleJobCents: 120_000, example: pct(1000, 50_000, 5_000) },
  { slug: "dakdekkers", nameNl: "Dakdekkers", nameEn: "Roofers", descriptionNl: "Dakrenovatie, bitumen, dakpannen, dakgoten.", descriptionEn: "Roof renovation, bitumen, tiles, gutters.", whoNl: "Iemand met een lekkend dak of een plat dak dat aan vervanging toe is.", whoEn: "Someone with a leaking roof or a flat roof due for replacement.", exampleJobCents: 800_000, example: pct(600) },
  { slug: "elektriciens", nameNl: "Elektriciens", nameEn: "Electricians", descriptionNl: "Groepenkast, bekabeling, laadpalen, verlichting.", descriptionEn: "Fuse boxes, wiring, EV chargers, lighting.", whoNl: "Iemand die een laadpaal wil, of een groepenkast die te klein is.", whoEn: "Someone who wants an EV charger, or has an undersized fuse box.", exampleJobCents: 250_000, example: pct(800) },
  { slug: "installateurs", nameNl: "Installateurs (cv/warmtepomp)", nameEn: "Installers (heating/heat pumps)", descriptionNl: "Cv-ketels, warmtepompen, airco, ventilatie.", descriptionEn: "Boilers, heat pumps, air conditioning, ventilation.", whoNl: "Iemand met een oude cv-ketel of die wil verduurzamen.", whoEn: "Someone with an old boiler or who wants to go sustainable.", exampleJobCents: 900_000, example: pct(500) },
  { slug: "zonnepanelen", nameNl: "Zonnepanelen", nameEn: "Solar panels", descriptionNl: "Zonnepanelen, omvormers, thuisbatterijen.", descriptionEn: "Solar panels, inverters, home batteries.", whoNl: "Huiseigenaren met een geschikt dak die hun energierekening omlaag willen.", whoEn: "Homeowners with a suitable roof who want lower energy bills.", exampleJobCents: 700_000, example: { feeType: "TIERED", tiers: [{ fromCents: 300_000, feeCents: 20_000 }, { fromCents: 1_000_000, feeCents: 35_000 }], minJobAmountCents: 300_000, minFeeCents: 5_000 } },
  { slug: "badkamers", nameNl: "Badkamers", nameEn: "Bathrooms", descriptionNl: "Complete badkamerrenovatie, tegelwerk, sanitair.", descriptionEn: "Complete bathroom renovation, tiling, fixtures.", whoNl: "Iemand met een gedateerde badkamer of een nieuwbouwwoning.", whoEn: "Someone with a dated bathroom or a new-build home.", exampleJobCents: 1_200_000, example: pct(400) },
  { slug: "keukens", nameNl: "Keukens", nameEn: "Kitchens", descriptionNl: "Keukens op maat, montage, werkbladen, apparatuur.", descriptionEn: "Custom kitchens, fitting, worktops, appliances.", whoNl: "Iemand die verhuist of zijn keuken wil vervangen.", whoEn: "Someone moving house or replacing their kitchen.", exampleJobCents: 1_500_000, example: { feeType: "TIERED", tiers: [{ fromCents: 500_000, feeCents: 15_000 }, { fromCents: 1_000_000, feeCents: 30_000 }, { fromCents: 2_000_000, feeCents: 50_000 }], minJobAmountCents: 500_000, minFeeCents: 5_000 } },
  { slug: "kozijnen", nameNl: "Kozijnen", nameEn: "Window frames", descriptionNl: "Kunststof, houten en aluminium kozijnen, deuren, glas.", descriptionEn: "uPVC, wooden and aluminium frames, doors, glazing.", whoNl: "Iemand met tochtige ramen of enkel glas.", whoEn: "Someone with draughty windows or single glazing.", exampleJobCents: 1_000_000, example: pct(400) },
  { slug: "hoveniers", nameNl: "Hoveniers", nameEn: "Gardeners", descriptionNl: "Tuinaanleg, bestrating, onderhoud, schuttingen.", descriptionEn: "Garden design, paving, maintenance, fencing.", whoNl: "Iemand die een nieuwe tuin wil of net een huis met tuin kocht.", whoEn: "Someone who wants a new garden or just bought a house with one.", exampleJobCents: 600_000, example: pct(700) },
  { slug: "schoonmaakbedrijven", nameNl: "Schoonmaakbedrijven", nameEn: "Cleaning companies", descriptionNl: "Kantoorschoonmaak, glasbewassing, opleveringsschoonmaak.", descriptionEn: "Office cleaning, window cleaning, end-of-tenancy cleaning.", whoNl: "Een ondernemer die een schoonmaker zoekt voor zijn pand.", whoEn: "A business owner looking for a cleaner for their premises.", exampleJobCents: 300_000, example: fixed(10_000, 100_000) },
  { slug: "verhuizers", nameNl: "Verhuizers", nameEn: "Movers", descriptionNl: "Particuliere en zakelijke verhuizingen, opslag.", descriptionEn: "Private and business moves, storage.", whoNl: "Iemand die binnenkort gaat verhuizen.", whoEn: "Someone moving house soon.", exampleJobCents: 150_000, example: pct(1000) },
  { slug: "autodealers", nameNl: "Autodealers", nameEn: "Car dealers", descriptionNl: "Nieuwe en gebruikte auto's, lease, inruil.", descriptionEn: "New and used cars, leasing, trade-ins.", whoNl: "Iemand die binnenkort een andere auto zoekt.", whoEn: "Someone looking for a different car soon.", exampleJobCents: 1_800_000, example: fixed(25_000, 300_000) },
  { slug: "autoschade-garages", nameNl: "Autoschade en garages", nameEn: "Car repair and garages", descriptionNl: "Schadeherstel, onderhoud, APK, banden.", descriptionEn: "Body repair, servicing, MOT, tyres.", whoNl: "Iemand met een deuk, kras of een auto die onderhoud nodig heeft.", whoEn: "Someone with a dent, scratch or a car due for service.", exampleJobCents: 120_000, example: pct(800, 50_000, 5_000) },
  { slug: "rijscholen", nameNl: "Rijscholen", nameEn: "Driving schools", descriptionNl: "Rijlessen auto en motor, pakketten, spoedopleidingen.", descriptionEn: "Car and motorcycle lessons, packages, intensive courses.", whoNl: "Iemand die net 17 is geworden, of wil beginnen met rijles.", whoEn: "Someone who just turned 17, or wants to start driving lessons.", exampleJobCents: 220_000, example: fixed(15_000, 100_000) },
  { slug: "sportscholen", nameNl: "Sportscholen", nameEn: "Gyms", descriptionNl: "Jaarabonnementen, personal training, groepslessen.", descriptionEn: "Annual memberships, personal training, group classes.", whoNl: "Iemand die wil beginnen met sporten of overstappen.", whoEn: "Someone who wants to start training or switch gyms.", exampleJobCents: 60_000, example: fixed(7_500, 40_000) },
  { slug: "trouwlocaties", nameNl: "Trouwlocaties", nameEn: "Wedding venues", descriptionNl: "Locaties voor ceremonie, diner en feest.", descriptionEn: "Venues for ceremony, dinner and party.", whoNl: "Een stel dat net verloofd is.", whoEn: "A couple that just got engaged.", exampleJobCents: 1_200_000, example: { feeType: "TIERED", tiers: [{ fromCents: 500_000, feeCents: 25_000 }, { fromCents: 1_500_000, feeCents: 50_000 }], minJobAmountCents: 500_000, minFeeCents: 5_000 } },
  { slug: "cateraars", nameNl: "Cateraars", nameEn: "Caterers", descriptionNl: "Catering voor feesten, bruiloften en bedrijfsevents.", descriptionEn: "Catering for parties, weddings and corporate events.", whoNl: "Iemand die een feest, bruiloft of bedrijfsuitje organiseert.", whoEn: "Someone organising a party, wedding or company outing.", exampleJobCents: 400_000, example: pct(700) },
  { slug: "fotografen", nameNl: "Fotografen", nameEn: "Photographers", descriptionNl: "Bruiloften, portretten, bedrijfsfotografie.", descriptionEn: "Weddings, portraits, corporate photography.", whoNl: "Een stel dat gaat trouwen, of een bedrijf dat nieuwe foto's nodig heeft.", whoEn: "A couple getting married, or a company that needs new photos.", exampleJobCents: 200_000, example: pct(1000) },
  { slug: "webdesign-marketing", nameNl: "Webdesign en marketing", nameEn: "Web design and marketing", descriptionNl: "Websites, webshops, online marketing.", descriptionEn: "Websites, web shops, online marketing.", whoNl: "Een ondernemer met een verouderde website of zonder online zichtbaarheid.", whoEn: "A business owner with an outdated website or no online presence.", exampleJobCents: 500_000, example: pct(1000) },
];

export const EXCLUDED_CATEGORIES = [
  { slug: "makelaardij", nameNl: "Makelaardij", nameEn: "Real estate brokerage", reasonNl: "Bemiddeling bij woningen kent eigen regels over provisies en belangenverstrengeling.", reasonEn: "Property brokerage has its own rules on commissions and conflicts of interest." },
  { slug: "hypotheken", nameNl: "Hypotheken", nameEn: "Mortgages", reasonNl: "Financieel advies en bemiddeling vallen onder de Wft en het provisieverbod.", reasonEn: "Financial advice and brokerage fall under the Dutch Wft and its commission ban." },
  { slug: "verzekeringen", nameNl: "Verzekeringen", nameEn: "Insurance", reasonNl: "Aanbrengen van verzekeringen is vergunningsplichtig bemiddelen onder de Wft.", reasonEn: "Introducing insurance counts as regulated intermediation under the Wft." },
  { slug: "financiele-producten", nameNl: "Overige financiële producten", nameEn: "Other financial products", reasonNl: "Leningen, beleggingen en vergelijkbare producten vallen onder financieel toezicht.", reasonEn: "Loans, investments and similar products are under financial supervision." },
  { slug: "advocatuur", nameNl: "Advocatuur", nameEn: "Legal services", reasonNl: "Advocaten mogen geen vergoeding betalen voor het aanbrengen van cliënten.", reasonEn: "Lawyers may not pay fees for introducing clients." },
  { slug: "medische-zorg", nameNl: "Medische zorg", nameEn: "Medical care", reasonNl: "Betaald doorverwijzen naar zorgverleners is onwenselijk en deels verboden.", reasonEn: "Paid referral to healthcare providers is undesirable and partly prohibited." },
];
