/**
 * All 12 provinces and 342 municipalities of the Netherlands (CBS / Wikipedia, population at
 * 1 January 2024). Every municipality gets its own landing page, so someone searching
 * "klanten aanbrengen Zwolle" or "finder's fee Tilburg" lands on a page about their own town.
 */
export type ProvinceKey =
  | "drenthe" | "flevoland" | "friesland" | "gelderland" | "groningen" | "limburg"
  | "noord-brabant" | "noord-holland" | "overijssel" | "utrecht" | "zeeland" | "zuid-holland";

export const PROVINCES: { key: ProvinceKey; name: string; capital: string }[] = [
  { key: "drenthe", name: "Drenthe", capital: "Assen" },
  { key: "flevoland", name: "Flevoland", capital: "Lelystad" },
  { key: "friesland", name: "Friesland", capital: "Leeuwarden" },
  { key: "gelderland", name: "Gelderland", capital: "Arnhem" },
  { key: "groningen", name: "Groningen", capital: "Groningen" },
  { key: "limburg", name: "Limburg", capital: "Maastricht" },
  { key: "noord-brabant", name: "Noord-Brabant", capital: "'s-Hertogenbosch" },
  { key: "noord-holland", name: "Noord-Holland", capital: "Haarlem" },
  { key: "overijssel", name: "Overijssel", capital: "Zwolle" },
  { key: "utrecht", name: "Utrecht", capital: "Utrecht" },
  { key: "zeeland", name: "Zeeland", capital: "Middelburg" },
  { key: "zuid-holland", name: "Zuid-Holland", capital: "Den Haag" },
];

export interface Municipality {
  slug: string;
  name: string;
  seat: string;
  province: ProvinceKey;
  population: number;
}

const ROWS: [string, string, string, ProvinceKey, number][] = [
  ["aa-en-hunze", "Aa en Hunze", "Gieten", "drenthe", 26057],
  ["aalsmeer", "Aalsmeer", "Aalsmeer", "noord-holland", 33453],
  ["aalten", "Aalten", "Aalten", "gelderland", 27603],
  ["achtkarspelen", "Achtkarspelen", "Buitenpost", "friesland", 28253],
  ["alblasserdam", "Alblasserdam", "Alblasserdam", "zuid-holland", 20239],
  ["albrandswaard", "Albrandswaard", "Rhoon", "zuid-holland", 26560],
  ["alkmaar", "Alkmaar", "Alkmaar", "noord-holland", 113170],
  ["almelo", "Almelo", "Almelo", "overijssel", 75158],
  ["almere", "Almere", "Almere", "flevoland", 232650],
  ["alphen-aan-den-rijn", "Alphen aan den Rijn", "Alphen aan den Rijn", "zuid-holland", 117278],
  ["alphen-chaam", "Alphen-Chaam", "Alphen", "noord-brabant", 10489],
  ["altena", "Altena", "Almkerk", "noord-brabant", 58957],
  ["ameland", "Ameland", "Ballum", "friesland", 3822],
  ["amersfoort", "Amersfoort", "Amersfoort", "utrecht", 163766],
  ["amstelveen", "Amstelveen", "Amstelveen", "noord-holland", 95836],
  ["amsterdam", "Amsterdam", "Amsterdam", "noord-holland", 942504],
  ["apeldoorn", "Apeldoorn", "Apeldoorn", "gelderland", 169222],
  ["arnhem", "Arnhem", "Arnhem", "gelderland", 172002],
  ["assen", "Assen", "Assen", "drenthe", 70765],
  ["asten", "Asten", "Asten", "noord-brabant", 17493],
  ["baarle-nassau", "Baarle-Nassau", "Baarle-Nassau", "noord-brabant", 7254],
  ["baarn", "Baarn", "Baarn", "utrecht", 25442],
  ["barendrecht", "Barendrecht", "Barendrecht", "zuid-holland", 48678],
  ["barneveld", "Barneveld", "Barneveld", "gelderland", 63927],
  ["beek", "Beek", "Beek", "limburg", 16143],
  ["beekdaelen", "Beekdaelen", "Nuth", "limburg", 35915],
  ["beesel", "Beesel", "Reuver", "limburg", 13569],
  ["berg-en-dal", "Berg en Dal", "Groesbeek", "gelderland", 35706],
  ["bergeijk", "Bergeijk", "Bergeijk", "noord-brabant", 19440],
  ["bergen", "Bergen", "Nieuw Bergen", "limburg", 13038],
  ["bergen", "Bergen", "Alkmaar", "noord-holland", 29654],
  ["bergen-op-zoom", "Bergen op Zoom", "Bergen op Zoom", "noord-brabant", 70693],
  ["berkelland", "Berkelland", "Borculo", "gelderland", 43990],
  ["bernheze", "Bernheze", "Heesch", "noord-brabant", 32943],
  ["best", "Best", "Best", "noord-brabant", 31694],
  ["beuningen", "Beuningen", "Beuningen", "gelderland", 26871],
  ["beverwijk", "Beverwijk", "Beverwijk", "noord-holland", 43063],
  ["bladel", "Bladel", "Bladel", "noord-brabant", 21046],
  ["blaricum", "Blaricum", "Blaricum", "noord-holland", 12934],
  ["bloemendaal", "Bloemendaal", "Overveen", "noord-holland", 23558],
  ["bodegraven-reeuwijk", "Bodegraven-Reeuwijk", "Bodegraven", "zuid-holland", 37292],
  ["boekel", "Boekel", "Boekel", "noord-brabant", 11685],
  ["borger-odoorn", "Borger-Odoorn", "Exloo", "drenthe", 26161],
  ["borne", "Borne", "Borne", "overijssel", 25042],
  ["borsele", "Borsele", "Heinkenszand", "zeeland", 23185],
  ["boxtel", "Boxtel", "Boxtel", "noord-brabant", 34314],
  ["breda", "Breda", "Breda", "noord-brabant", 190171],
  ["bronckhorst", "Bronckhorst", "Hengelo", "gelderland", 35981],
  ["brummen", "Brummen", "Brummen", "gelderland", 21561],
  ["brunssum", "Brunssum", "Brunssum", "limburg", 27481],
  ["bunnik", "Bunnik", "Odijk", "utrecht", 16402],
  ["bunschoten", "Bunschoten", "Bunschoten-Spakenburg", "utrecht", 22899],
  ["buren", "Buren", "Maurik", "gelderland", 28096],
  ["capelle-aan-den-ijssel", "Capelle aan den IJssel", "Capelle aan den IJssel", "zuid-holland", 69644],
  ["castricum", "Castricum", "Castricum", "noord-holland", 37075],
  ["coevorden", "Coevorden", "Coevorden", "drenthe", 35726],
  ["cranendonck", "Cranendonck", "Budel", "noord-brabant", 21025],
  ["culemborg", "Culemborg", "Culemborg", "gelderland", 30409],
  ["dalfsen", "Dalfsen", "Dalfsen", "overijssel", 30268],
  ["dantumadeel", "Dantumadeel", "Damwoude", "friesland", 19241],
  ["de-bilt", "De Bilt", "Bilthoven", "utrecht", 43673],
  ["de-friese-meren", "De Friese Meren", "Joure", "friesland", 52253],
  ["de-ronde-venen", "De Ronde Venen", "Mijdrecht", "utrecht", 45739],
  ["de-wolden", "De Wolden", "Zuidwolde", "drenthe", 24826],
  ["delft", "Delft", "Delft", "zuid-holland", 110044],
  ["den-haag", "Den Haag", "Den Haag", "zuid-holland", 569076],
  ["den-helder", "Den Helder", "Den Helder", "noord-holland", 56665],
  ["deurne", "Deurne", "Deurne", "noord-brabant", 33597],
  ["deventer", "Deventer", "Deventer", "overijssel", 105130],
  ["diemen", "Diemen", "Diemen", "noord-holland", 33284],
  ["dijk-en-waard", "Dijk en Waard", "Heerhugowaard", "noord-holland", 91431],
  ["dinkelland", "Dinkelland", "Denekamp", "overijssel", 26969],
  ["doesburg", "Doesburg", "Doesburg", "gelderland", 11172],
  ["doetinchem", "Doetinchem", "Doetinchem", "gelderland", 60473],
  ["dongen", "Dongen", "Dongen", "noord-brabant", 27607],
  ["dordrecht", "Dordrecht", "Dordrecht", "zuid-holland", 122933],
  ["drechterland", "Drechterland", "Hoogkarspel", "noord-holland", 20553],
  ["drimmelen", "Drimmelen", "Made", "noord-brabant", 28399],
  ["dronten", "Dronten", "Dronten", "flevoland", 45436],
  ["druten", "Druten", "Druten", "gelderland", 20015],
  ["duiven", "Duiven", "Duiven", "gelderland", 24856],
  ["echt-susteren", "Echt-Susteren", "Echt", "limburg", 32394],
  ["edam-volendam", "Edam-Volendam", "Volendam", "noord-holland", 37124],
  ["ede", "Ede", "Ede", "gelderland", 125303],
  ["eemnes", "Eemnes", "Eemnes", "utrecht", 10063],
  ["eemsdelta", "Eemsdelta", "Delfzijl", "groningen", 44841],
  ["eersel", "Eersel", "Eersel", "noord-brabant", 20539],
  ["eijsden-margraten", "Eijsden-Margraten", "Margraten", "limburg", 26346],
  ["eindhoven", "Eindhoven", "Eindhoven", "noord-brabant", 249873],
  ["elburg", "Elburg", "Elburg", "gelderland", 24039],
  ["emmen", "Emmen", "Emmen", "drenthe", 109838],
  ["enkhuizen", "Enkhuizen", "Enkhuizen", "noord-holland", 18738],
  ["enschede", "Enschede", "Enschede", "overijssel", 162671],
  ["epe", "Epe", "Epe", "gelderland", 33781],
  ["ermelo", "Ermelo", "Ermelo", "gelderland", 28191],
  ["etten-leur", "Etten-Leur", "Etten-Leur", "noord-brabant", 46109],
  ["geertruidenberg", "Geertruidenberg", "Geertruidenberg", "noord-brabant", 21914],
  ["geldrop-mierlo", "Geldrop-Mierlo", "Geldrop", "noord-brabant", 40683],
  ["gemert-bakel", "Gemert-Bakel", "Gemert", "noord-brabant", 31812],
  ["gennep", "Gennep", "Gennep", "limburg", 17957],
  ["gilze-en-rijen", "Gilze en Rijen", "Rijen", "noord-brabant", 28361],
  ["goeree-overflakkee", "Goeree-Overflakkee", "Middelharnis", "zuid-holland", 52775],
  ["goes", "Goes", "Goes", "zeeland", 40399],
  ["goirle", "Goirle", "Goirle", "noord-brabant", 24891],
  ["gooise-meren", "Gooise Meren", "Bussum", "noord-holland", 61213],
  ["gorinchem", "Gorinchem", "Gorinchem", "zuid-holland", 39046],
  ["gouda", "Gouda", "Gouda", "zuid-holland", 77803],
  ["groningen", "Groningen", "Groningen", "groningen", 244829],
  ["gulpen-wittem", "Gulpen-Wittem", "Gulpen", "limburg", 13944],
  ["haaksbergen", "Haaksbergen", "Haaksbergen", "overijssel", 24313],
  ["haarlem", "Haarlem", "Haarlem", "noord-holland", 168946],
  ["haarlemmermeer", "Haarlemmermeer", "Hoofddorp", "noord-holland", 166996],
  ["halderberge", "Halderberge", "Oudenbosch", "noord-brabant", 31477],
  ["hardenberg", "Hardenberg", "Hardenberg", "overijssel", 64120],
  ["harderwijk", "Harderwijk", "Harderwijk", "gelderland", 50661],
  ["hardinxveld-giessendam", "Hardinxveld-Giessendam", "Neder-Hardinxveld", "zuid-holland", 19400],
  ["harlingen", "Harlingen", "Harlingen", "friesland", 16270],
  ["hattem", "Hattem", "Hattem", "gelderland", 12822],
  ["heemskerk", "Heemskerk", "Heemskerk", "noord-holland", 39532],
  ["heemstede", "Heemstede", "Heemstede", "noord-holland", 27557],
  ["heerde", "Heerde", "Heerde", "gelderland", 19325],
  ["heerenveen", "Heerenveen", "Heerenveen", "friesland", 51961],
  ["heerlen", "Heerlen", "Heerlen", "limburg", 87754],
  ["heeze-leende", "Heeze-Leende", "Heeze", "noord-brabant", 17271],
  ["heiloo", "Heiloo", "Heiloo", "noord-holland", 24612],
  ["hellendoorn", "Hellendoorn", "Nijverdal", "overijssel", 36351],
  ["helmond", "Helmond", "Helmond", "noord-brabant", 96842],
  ["hendrik-ido-ambacht", "Hendrik-Ido-Ambacht", "Hendrik-Ido-Ambacht", "zuid-holland", 33107],
  ["hengelo", "Hengelo", "Hengelo", "overijssel", 84038],
  ["het-hogeland", "Het Hogeland", "Uithuizen", "groningen", 48074],
  ["heumen", "Heumen", "Malden", "gelderland", 16977],
  ["heusden", "Heusden", "Vlijmen", "noord-brabant", 46687],
  ["hillegom", "Hillegom", "Hillegom", "zuid-holland", 23083],
  ["hilvarenbeek", "Hilvarenbeek", "Hilvarenbeek", "noord-brabant", 16313],
  ["hilversum", "Hilversum", "Hilversum", "noord-holland", 94601],
  ["hoeksche-waard", "Hoeksche Waard", "Oud-Beijerland", "zuid-holland", 91448],
  ["hof-van-twente", "Hof van Twente", "Goor", "overijssel", 35773],
  ["hollands-kroon", "Hollands Kroon", "Anna Paulowna", "noord-holland", 50619],
  ["hoogeveen", "Hoogeveen", "Hoogeveen", "drenthe", 56773],
  ["hoorn", "Hoorn", "Hoorn", "noord-holland", 76211],
  ["horst-aan-de-maas", "Horst aan de Maas", "Horst", "limburg", 44805],
  ["houten", "Houten", "Houten", "utrecht", 50950],
  ["huizen", "Huizen", "Huizen", "noord-holland", 41283],
  ["hulst", "Hulst", "Hulst", "zeeland", 27375],
  ["ijsselstein", "IJsselstein", "IJsselstein", "utrecht", 33171],
  ["kaag-en-braassem", "Kaag en Braassem", "Roelofarendsveen", "zuid-holland", 29472],
  ["kampen", "Kampen", "Kampen", "overijssel", 56841],
  ["kapelle", "Kapelle", "Kapelle", "zeeland", 13156],
  ["katwijk", "Katwijk", "Katwijk", "zuid-holland", 67154],
  ["kerkrade", "Kerkrade", "Kerkrade", "limburg", 45823],
  ["koggenland", "Koggenland", "De Goorn", "noord-holland", 24209],
  ["krimpen-aan-den-ijssel", "Krimpen aan den IJssel", "Krimpen aan den IJssel", "zuid-holland", 29869],
  ["krimpenerwaard", "Krimpenerwaard", "Stolwijk", "zuid-holland", 57894],
  ["laarbeek", "Laarbeek", "Beek en Donk", "noord-brabant", 23543],
  ["land-van-cuijk", "Land van Cuijk", "Boxmeer", "noord-brabant", 93661],
  ["landgraaf", "Landgraaf", "Landgraaf", "limburg", 36838],
  ["landsmeer", "Landsmeer", "Landsmeer", "noord-holland", 11684],
  ["lansingerland", "Lansingerland", "Bergschenhoek", "zuid-holland", 66613],
  ["laren", "Laren", "Laren", "noord-holland", 11545],
  ["leeuwarden", "Leeuwarden", "Leeuwarden", "friesland", 130179],
  ["leiden", "Leiden", "Leiden", "zuid-holland", 130302],
  ["leiderdorp", "Leiderdorp", "Leiderdorp", "zuid-holland", 27946],
  ["leidschendam-voorburg", "Leidschendam-Voorburg", "Leidschendam", "zuid-holland", 78915],
  ["lelystad", "Lelystad", "Lelystad", "flevoland", 85758],
  ["leudal", "Leudal", "Heythuysen", "limburg", 36110],
  ["leusden", "Leusden", "Leusden", "utrecht", 32288],
  ["lingewaard", "Lingewaard", "Bemmel", "gelderland", 47804],
  ["lisse", "Lisse", "Lisse", "zuid-holland", 23843],
  ["lochem", "Lochem", "Lochem", "gelderland", 34213],
  ["loon-op-zand", "Loon op Zand", "Kaatsheuvel", "noord-brabant", 24112],
  ["lopik", "Lopik", "Lopik", "utrecht", 14796],
  ["losser", "Losser", "Losser", "overijssel", 23465],
  ["maasdriel", "Maasdriel", "Kerkdriel", "gelderland", 26225],
  ["maasgouw", "Maasgouw", "Maasbracht", "limburg", 24381],
  ["maashorst", "Maashorst", "Uden", "noord-brabant", 60060],
  ["maassluis", "Maassluis", "Maassluis", "zuid-holland", 37136],
  ["maastricht", "Maastricht", "Maastricht", "limburg", 126017],
  ["medemblik", "Medemblik", "Wognum", "noord-holland", 46328],
  ["meerssen", "Meerssen", "Meerssen", "limburg", 18453],
  ["meierijstad", "Meierijstad", "Sint-Oedenrode", "noord-brabant", 85249],
  ["meppel", "Meppel", "Meppel", "drenthe", 36607],
  ["middelburg", "Middelburg", "Middelburg", "zeeland", 50438],
  ["midden-delfland", "Midden-Delfland", "Schipluiden", "zuid-holland", 19359],
  ["midden-drenthe", "Midden-Drenthe", "Beilen", "drenthe", 34404],
  ["midden-groningen", "Midden-Groningen", "Hoogezand", "groningen", 61350],
  ["moerdijk", "Moerdijk", "Zevenbergen", "noord-brabant", 38470],
  ["molenlanden", "Molenlanden", "Bleskensgraaf", "zuid-holland", 45618],
  ["montferland", "Montferland", "Didam", "gelderland", 37008],
  ["montfoort", "Montfoort", "Montfoort", "utrecht", 13793],
  ["mook-en-middelaar", "Mook en Middelaar", "Mook", "limburg", 8190],
  ["neder-betuwe", "Neder-Betuwe", "Opheusden", "gelderland", 25920],
  ["nederweert", "Nederweert", "Nederweert", "limburg", 17537],
  ["nieuwegein", "Nieuwegein", "Nieuwegein", "utrecht", 68299],
  ["nieuwkoop", "Nieuwkoop", "Nieuwveen", "zuid-holland", 29719],
  ["nijkerk", "Nijkerk", "Nijkerk", "gelderland", 46276],
  ["nijmegen", "Nijmegen", "Nijmegen", "gelderland", 189850],
  ["nissewaard", "Nissewaard", "Spijkenisse", "zuid-holland", 89111],
  ["noardeast-fryslan", "Noardeast-Fryslân", "Dokkum", "friesland", 45933],
  ["noord-beveland", "Noord-Beveland", "Wissenkerke", "zeeland", 8071],
  ["noordenveld", "Noordenveld", "Roden", "drenthe", 31737],
  ["noordoostpolder", "Noordoostpolder", "Emmeloord", "flevoland", 51997],
  ["noordwijk", "Noordwijk", "Noordwijk", "zuid-holland", 46453],
  ["nuenen-c-a", "Nuenen c.a.", "Nuenen", "noord-brabant", 24467],
  ["nunspeet", "Nunspeet", "Nunspeet", "gelderland", 29686],
  ["oegstgeest", "Oegstgeest", "Oegstgeest", "zuid-holland", 26096],
  ["oirschot", "Oirschot", "Oirschot", "noord-brabant", 19795],
  ["oisterwijk", "Oisterwijk", "Oisterwijk", "noord-brabant", 33347],
  ["oldambt", "Oldambt", "Winschoten", "groningen", 39734],
  ["oldebroek", "Oldebroek", "Oldebroek", "gelderland", 24529],
  ["oldenzaal", "Oldenzaal", "Oldenzaal", "overijssel", 32029],
  ["olst-wijhe", "Olst-Wijhe", "Wijhe", "overijssel", 19078],
  ["ommen", "Ommen", "Ommen", "overijssel", 19368],
  ["oost-gelre", "Oost Gelre", "Lichtenvoorde", "gelderland", 29876],
  ["oosterhout", "Oosterhout", "Oosterhout", "noord-brabant", 58739],
  ["ooststellingwerf", "Ooststellingwerf", "Oosterwolde", "friesland", 25900],
  ["oostzaan", "Oostzaan", "Oostzaan", "noord-holland", 9776],
  ["opmeer", "Opmeer", "Opmeer", "noord-holland", 12668],
  ["opsterland", "Opsterland", "Beetsterzwaag", "friesland", 30073],
  ["oss", "Oss", "Oss", "noord-brabant", 95540],
  ["oude-ijsselstreek", "Oude IJsselstreek", "Gendringen", "gelderland", 39602],
  ["ouder-amstel", "Ouder-Amstel", "Ouderkerk aan de Amstel", "noord-holland", 14529],
  ["oudewater", "Oudewater", "Oudewater", "utrecht", 10512],
  ["overbetuwe", "Overbetuwe", "Elst", "gelderland", 49259],
  ["papendrecht", "Papendrecht", "Papendrecht", "zuid-holland", 32258],
  ["peel-en-maas", "Peel en Maas", "Panningen", "limburg", 45819],
  ["pekela", "Pekela", "Oude Pekela", "groningen", 12565],
  ["pijnacker-nootdorp", "Pijnacker-Nootdorp", "Pijnacker", "zuid-holland", 58749],
  ["purmerend", "Purmerend", "Purmerend", "noord-holland", 96177],
  ["putten", "Putten", "Putten", "gelderland", 25169],
  ["raalte", "Raalte", "Raalte", "overijssel", 39090],
  ["reimerswaal", "Reimerswaal", "Kruiningen", "zeeland", 23393],
  ["renkum", "Renkum", "Oosterbeek", "gelderland", 31355],
  ["renswoude", "Renswoude", "Renswoude", "utrecht", 5905],
  ["reusel-de-mierden", "Reusel-De Mierden", "Reusel", "noord-brabant", 13726],
  ["rheden", "Rheden", "De Steeg", "gelderland", 43848],
  ["rhenen", "Rhenen", "Rhenen", "utrecht", 20457],
  ["ridderkerk", "Ridderkerk", "Ridderkerk", "zuid-holland", 48070],
  ["rijssen-holten", "Rijssen-Holten", "Rijssen", "overijssel", 39270],
  ["rijswijk", "Rijswijk", "Rijswijk", "zuid-holland", 61874],
  ["roerdalen", "Roerdalen", "Sint Odiliënberg", "limburg", 20987],
  ["roermond", "Roermond", "Roermond", "limburg", 61439],
  ["roosendaal", "Roosendaal", "Roosendaal", "noord-brabant", 78171],
  ["rotterdam", "Rotterdam", "Rotterdam", "zuid-holland", 674485],
  ["rozendaal", "Rozendaal", "Rozendaal", "gelderland", 1836],
  ["rucphen", "Rucphen", "Rucphen", "noord-brabant", 23984],
  ["s-hertogenbosch", "'s-Hertogenbosch", "'s-Hertogenbosch", "noord-brabant", 162272],
  ["schagen", "Schagen", "Schagen", "noord-holland", 48772],
  ["scherpenzeel", "Scherpenzeel", "Scherpenzeel", "gelderland", 10674],
  ["schiedam", "Schiedam", "Schiedam", "zuid-holland", 82055],
  ["schiermonnikoog", "Schiermonnikoog", "Schiermonnikoog", "friesland", 971],
  ["schouwen-duiveland", "Schouwen-Duiveland", "Zierikzee", "zeeland", 34398],
  ["simpelveld", "Simpelveld", "Simpelveld", "limburg", 10462],
  ["sint-michielsgestel", "Sint-Michielsgestel", "Sint-Michielsgestel", "noord-brabant", 30191],
  ["sittard-geleen", "Sittard-Geleen", "Sittard", "limburg", 92428],
  ["sliedrecht", "Sliedrecht", "Sliedrecht", "zuid-holland", 26516],
  ["sluis", "Sluis", "Oostburg", "zeeland", 23191],
  ["smallingerland", "Smallingerland", "Drachten", "friesland", 57195],
  ["soest", "Soest", "Soest", "utrecht", 47853],
  ["someren", "Someren", "Someren", "noord-brabant", 20455],
  ["son-en-breugel", "Son en Breugel", "Son", "noord-brabant", 18140],
  ["stadskanaal", "Stadskanaal", "Stadskanaal", "groningen", 32110],
  ["staphorst", "Staphorst", "Staphorst", "overijssel", 18220],
  ["stede-broec", "Stede Broec", "Bovenkarspel", "noord-holland", 22435],
  ["steenbergen", "Steenbergen", "Steenbergen", "noord-brabant", 24588],
  ["steenwijkerland", "Steenwijkerland", "Steenwijk", "overijssel", 45925],
  ["stein", "Stein", "Stein", "limburg", 24691],
  ["stichtse-vecht", "Stichtse Vecht", "Maarssen", "utrecht", 66193],
  ["sudwest-fryslan", "Súdwest-Fryslân", "Sneek", "friesland", 90514],
  ["terneuzen", "Terneuzen", "Terneuzen", "zeeland", 55942],
  ["terschelling", "Terschelling", "West-Terschelling", "friesland", 4834],
  ["texel", "Texel", "Den Burg", "noord-holland", 13946],
  ["teylingen", "Teylingen", "Voorhout", "zuid-holland", 38744],
  ["tholen", "Tholen", "Tholen", "zeeland", 27032],
  ["tiel", "Tiel", "Tiel", "gelderland", 42493],
  ["tietjerksteradeel", "Tietjerksteradeel", "Bergum", "friesland", 32892],
  ["tilburg", "Tilburg", "Tilburg", "noord-brabant", 230757],
  ["tubbergen", "Tubbergen", "Tubbergen", "overijssel", 21601],
  ["twenterand", "Twenterand", "Vriezenveen", "overijssel", 34234],
  ["tynaarlo", "Tynaarlo", "Vries", "drenthe", 35118],
  ["uitgeest", "Uitgeest", "Uitgeest", "noord-holland", 13491],
  ["uithoorn", "Uithoorn", "Uithoorn", "noord-holland", 32215],
  ["urk", "Urk", "Urk", "flevoland", 22429],
  ["utrecht", "Utrecht", "Utrecht", "utrecht", 378278],
  ["utrechtse-heuvelrug", "Utrechtse Heuvelrug", "Doorn", "utrecht", 51104],
  ["vaals", "Vaals", "Vaals", "limburg", 10114],
  ["valkenburg-aan-de-geul", "Valkenburg aan de Geul", "Valkenburg", "limburg", 16490],
  ["valkenswaard", "Valkenswaard", "Valkenswaard", "noord-brabant", 31912],
  ["veendam", "Veendam", "Veendam", "groningen", 27826],
  ["veenendaal", "Veenendaal", "Veenendaal", "utrecht", 70799],
  ["veere", "Veere", "Domburg", "zeeland", 22041],
  ["veldhoven", "Veldhoven", "Veldhoven", "noord-brabant", 47902],
  ["velsen", "Velsen", "IJmuiden", "noord-holland", 70368],
  ["venlo", "Venlo", "Venlo", "limburg", 104201],
  ["venray", "Venray", "Venray", "limburg", 45104],
  ["vijfheerenlanden", "Vijfheerenlanden", "Leerdam", "utrecht", 63261],
  ["vlaardingen", "Vlaardingen", "Vlaardingen", "zuid-holland", 77462],
  ["vlieland", "Vlieland", "Oost-Vlieland", "friesland", 1204],
  ["vlissingen", "Vlissingen", "Vlissingen", "zeeland", 45893],
  ["voerendaal", "Voerendaal", "Voerendaal", "limburg", 12435],
  ["voorne-aan-zee", "Voorne aan Zee", "Hellevoetsluis", "zuid-holland", 73993],
  ["voorschoten", "Voorschoten", "Voorschoten", "zuid-holland", 25978],
  ["voorst", "Voorst", "Twello", "gelderland", 25567],
  ["vught", "Vught", "Vught", "noord-brabant", 33200],
  ["waadhoeke", "Waadhoeke", "Franeker", "friesland", 47164],
  ["waalre", "Waalre", "Waalre", "noord-brabant", 17862],
  ["waalwijk", "Waalwijk", "Waalwijk", "noord-brabant", 51638],
  ["waddinxveen", "Waddinxveen", "Waddinxveen", "zuid-holland", 35525],
  ["wageningen", "Wageningen", "Wageningen", "gelderland", 42784],
  ["wassenaar", "Wassenaar", "Wassenaar", "zuid-holland", 27975],
  ["waterland", "Waterland", "Monnickendam", "noord-holland", 17728],
  ["weert", "Weert", "Weert", "limburg", 51497],
  ["west-betuwe", "West Betuwe", "Geldermalsen", "gelderland", 53441],
  ["west-maas-en-waal", "West Maas en Waal", "Beneden-Leeuwen", "gelderland", 20838],
  ["westerkwartier", "Westerkwartier", "Zuidhorn", "groningen", 65065],
  ["westerveld", "Westerveld", "Diever", "drenthe", 20042],
  ["westervoort", "Westervoort", "Westervoort", "gelderland", 15250],
  ["westerwolde", "Westerwolde", "Sellingen", "groningen", 25136],
  ["westland", "Westland", "Naaldwijk", "zuid-holland", 118795],
  ["weststellingwerf", "Weststellingwerf", "Wolvega", "friesland", 26617],
  ["wierden", "Wierden", "Wierden", "overijssel", 25535],
  ["wijchen", "Wijchen", "Wijchen", "gelderland", 42104],
  ["wijdemeren", "Wijdemeren", "Loosdrecht", "noord-holland", 24672],
  ["wijk-bij-duurstede", "Wijk bij Duurstede", "Wijk bij Duurstede", "utrecht", 23712],
  ["winterswijk", "Winterswijk", "Winterswijk", "gelderland", 29298],
  ["woensdrecht", "Woensdrecht", "Hoogerheide", "noord-brabant", 22305],
  ["woerden", "Woerden", "Woerden", "utrecht", 54208],
  ["wormerland", "Wormerland", "Wormer", "noord-holland", 16328],
  ["woudenberg", "Woudenberg", "Woudenberg", "utrecht", 15103],
  ["zaanstad", "Zaanstad", "Zaandam", "noord-holland", 165235],
  ["zaltbommel", "Zaltbommel", "Zaltbommel", "gelderland", 30677],
  ["zandvoort", "Zandvoort", "Zandvoort", "noord-holland", 17326],
  ["zeewolde", "Zeewolde", "Zeewolde", "flevoland", 24610],
  ["zeist", "Zeist", "Zeist", "utrecht", 66656],
  ["zevenaar", "Zevenaar", "Zevenaar", "gelderland", 45570],
  ["zoetermeer", "Zoetermeer", "Zoetermeer", "zuid-holland", 130850],
  ["zoeterwoude", "Zoeterwoude", "Zoeterwoude", "zuid-holland", 10357],
  ["zuidplas", "Zuidplas", "Nieuwerkerk aan den IJssel", "zuid-holland", 49294],
  ["zundert", "Zundert", "Zundert", "noord-brabant", 23088],
  ["zutphen", "Zutphen", "Zutphen", "gelderland", 49290],
  ["zwartewaterland", "Zwartewaterland", "Hasselt", "overijssel", 23737],
  ["zwijndrecht", "Zwijndrecht", "Zwijndrecht", "zuid-holland", 44816],
  ["zwolle", "Zwolle", "Zwolle", "overijssel", 134143],
];

export const MUNICIPALITIES: Municipality[] = ROWS.map(([slug, name, seat, province, population]) => ({ slug, name, seat, province, population }));

export function province(key: string) {
  return PROVINCES.find((p) => p.key === key);
}

export function municipalitiesIn(key: string): Municipality[] {
  return MUNICIPALITIES.filter((m) => m.province === key).sort((a, b) => b.population - a.population);
}

export function municipality(provinceKey: string, slug: string): Municipality | undefined {
  return MUNICIPALITIES.find((m) => m.province === provinceKey && m.slug === slug);
}

/** Nearby municipalities for internal links: the largest others in the same province. */
export function neighbours(m: Municipality, n = 8): Municipality[] {
  return municipalitiesIn(m.province).filter((x) => x.slug !== m.slug).slice(0, n);
}
